/* =====================================================================
   WORK COVER IMAGES — title pages, first editions and manuscripts.
   ---------------------------------------------------------------------
   Keyed by the `w` (Wikipedia title) field in works.js.

   Only freely-licensed images are listed. Every URL here is on
   upload.wikimedia.org/wikipedia/commons/, which means public domain or
   an open licence — copyrighted modern jackets are deliberately excluded.
   Entries that merely resolved to a portrait of the author, or to an
   unrelated illustration, have also been removed: a work with no accurate
   image is drawn as a printed title card instead.

   To add one, put the Commons file URL against the work's Wikipedia title.
   ===================================================================== */

const COVERS = {
 "A Letter Concerning Toleration":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Letter_Concerning_Toleration.jpg/330px-Letter_Concerning_Toleration.jpg",
 "A Philosophical Enquiry into the Origin of Our Ideas of the Sublime and Beautiful":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/A_philosophical_enquiry_into_the_origin_of_our_ideas_of_the_sublime_and_beautiful.jpg/330px-A_philosophical_enquiry_into_the_origin_of_our_ideas_of_the_sublime_and_beautiful.jpg",
 "A Theory of Justice":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/A_Theory_of_Justice_-_first_American_hardcover_edition.jpg/330px-A_Theory_of_Justice_-_first_American_hardcover_edition.jpg",
 "A Vindication of the Rights of Men":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/WollstonecraftVRM.jpg/330px-WollstonecraftVRM.jpg",
 "A Vindication of the Rights of Woman":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/A_Vindication_of_the_Rights_of_Woman_title_page.jpg/330px-A_Vindication_of_the_Rights_of_Woman_title_page.jpg",
 "A Week on the Concord and Merrimack Rivers":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/A_Week_on_the_Concord_and_Merrimack_Rivers%2C_1849.jpg/330px-A_Week_on_the_Concord_and_Merrimack_Rivers%2C_1849.jpg",
 "An Essay Concerning Human Understanding":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Locke_Essay_1690.jpg/330px-Locke_Essay_1690.jpg",
 "Analects":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Rongo_Analects_02.jpg/330px-Rongo_Analects_02.jpg",
 "Anarchy, State, and Utopia":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Anarchy%2C_State%2C_and_Utopia_%28first_edition%29.JPG/330px-Anarchy%2C_State%2C_and_Utopia_%28first_edition%29.JPG",
 "Animal Farm":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Animal_Farm_-_1st_edition.jpg/330px-Animal_Farm_-_1st_edition.jpg",
 "Anna Karenina":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/AnnaKareninaTitle.jpg/330px-AnnaKareninaTitle.jpg",
 "Annihilation of Caste":"https://upload.wikimedia.org/wikipedia/commons/9/99/First_edition_of_Annihilation_of_Caste.jpg",
 "Asa di Var":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Guru_Granth_Sahib_manuscript_housed_at_Sri_Keshgarh_Sahib%2C_Anandpur_and_dated_to_1803_B.S._%281746_C.E.%29_beautifully_decorated_with_gold_and_floral_arabesques_01.jpg/330px-thumbnail.jpg",
 "Barnaparichay":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Barnaparichay.jpg/330px-Barnaparichay.jpg",
 "Beyond Good and Evil":"https://upload.wikimedia.org/wikipedia/commons/c/c2/Jenseits_von_Gut_und_B%C3%B6se_-_1886.jpg",
 "Bhoodan movement":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Bhoodan_yojana.jpg/330px-Bhoodan_yojana.jpg",
 "Bijak":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/The_Bijak_of_Kabir.jpg/330px-The_Bijak_of_Kabir.jpg",
 "Book of Rites":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Annotated_Classic_of_Rites_59.jpg/330px-Annotated_Classic_of_Rites_59.jpg",
 "Concept of the Corporation":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Concept_of_corporation_book_cover.jpg/330px-Concept_of_corporation_book_cover.jpg",
 "Confessions (Rousseau)":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Confessions_Rousseau_Aldus_P028.jpg/330px-Confessions_Rousseau_Aldus_P028.jpg",
 "Considerations on Representative Government":"https://upload.wikimedia.org/wikipedia/commons/7/70/John_Stuart_Mill%2C_Considerations_on_Representative_Government_%281st_ed%2C_1861%2C_title_page%29.jpg",
 "Considerations on the Causes of the Greatness of the Romans and their Decline":"https://upload.wikimedia.org/wikipedia/commons/2/2f/Considerations_des_Romains_-_Montesquieu.jpg",
 "Crito":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Kriton_beginning._Clarke_Plato.jpg/330px-Kriton_beginning._Clarke_Plato.jpg",
 "Das Kapital":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Zentralbibliothek_Z%C3%BCrich_Das_Kapital_Marx_1867.jpg/330px-Zentralbibliothek_Z%C3%BCrich_Das_Kapital_Marx_1867.jpg",
 "Democracy in America":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Democracy_in_America_by_Alexis_de_Tocqueville_title_page.jpg/330px-Democracy_in_America_by_Alexis_de_Tocqueville_title_page.jpg",
 "Dhammacakkappavattana Sutta":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Sermon_in_the_Deer_Park_depicted_at_Wat_Chedi_Liem-KayEss-1.jpeg/330px-Sermon_in_the_Deer_Park_depicted_at_Wat_Chedi_Liem-KayEss-1.jpeg",
 "Dhammapada":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Folios_of_the_Bhikkhuni-patimokkha_%28BL_IO_Man.Pali_21%29.jpg/330px-Folios_of_the_Bhikkhuni-patimokkha_%28BL_IO_Man.Pali_21%29.jpg",
 "Discourse on Inequality":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/DOI_Rousseau.jpg/330px-DOI_Rousseau.jpg",
 "Discourses of Epictetus":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/The_Discourses_of_Epictetus_-_Elizabeth_Carter_-_1759_-_page_1.jpg/330px-The_Discourses_of_Epictetus_-_Elizabeth_Carter_-_1759_-_page_1.jpg",
 "Discourses on Livy":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Discorsi_di_Nicolo_Machiavelli%2C_firentino%2C_sopra_la_prima_deca_di_Tito_Livio.jpg/330px-Discorsi_di_Nicolo_Machiavelli%2C_firentino%2C_sopra_la_prima_deca_di_Tito_Livio.jpg",
 "Eichmann in Jerusalem":"https://upload.wikimedia.org/wikipedia/commons/b/be/Eichmann_in_Jerusalem_book_cover.jpg",
 "Elements of the Philosophy of Right":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Grundlinien_der_Philosophie_des_Rechts.jpg/330px-Grundlinien_der_Philosophie_des_Rechts.jpg",
 "Emile, or On Education":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/EmileTitle.jpeg/330px-EmileTitle.jpeg",
 "Enchiridion of Epictetus":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Epictetus_Enchiridion_1683_page1.jpg/330px-Epictetus_Enchiridion_1683_page1.jpg",
 "Guru Granth Sahib":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sri_Guru_Granth_Sahib_Nishan.jpg/330px-Sri_Guru_Granth_Sahib_Nishan.jpg",
 "Hind Swaraj or Indian Home Rule":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Gandhi-Home-Rule-First-Edition-1909.jpg/330px-Gandhi-Home-Rule-First-Edition-1909.jpg",
 "Jain literature":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/12th-century_Yogasastra%2C_Hemachandra_Jainism%2C_Sanskrit%2C_1_mm_Devanagari_script.jpg/330px-12th-century_Yogasastra%2C_Hemachandra_Jainism%2C_Sanskrit%2C_1_mm_Devanagari_script.jpg",
 "Japji Sahib":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Folio_of_the_Japji_Sahib_composition_of_the_Kartarpur_Bir.jpg/330px-Folio_of_the_Japji_Sahib_composition_of_the_Kartarpur_Bir.jpg",
 "Kudi Arasu":"https://upload.wikimedia.org/wikipedia/commons/3/39/Periyarkutiarasu.jpg",
 "Letter from Birmingham Jail":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Recreation_of_Martin_Luther_King%27s_Cell_in_Birmingham_Jail_-_National_Civil_Rights_Museum_-_Downtown_Memphis_-_Tennessee_-_USA.jpg/330px-Recreation_of_Martin_Luther_King%27s_Cell_in_Birmingham_Jail_-_National_Civil_Rights_Museum_-_Downtown_Memphis_-_Tennessee_-_USA.jpg",
 "Leviathan (Hobbes book)":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Leviathan_frontispiece_cropped_British_Museum.jpg/330px-Leviathan_frontispiece_cropped_British_Museum.jpg",
 "Maslow's hierarchy of needs":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Maslow%27s_Hierarchy_of_Needs_Diagram.png/330px-Maslow%27s_Hierarchy_of_Needs_Diagram.png",
 "Meditations":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Marcus_Aurelius._De_seipso%2C_seu_vita_sua_%28Xylander%2C_1558%29.jpg/330px-Marcus_Aurelius._De_seipso%2C_seu_vita_sua_%28Xylander%2C_1558%29.jpg",
 "Memorabilia (Xenophon)":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/G%C3%BCthling_Xenophon_Erinnerungen_001.jpg/330px-G%C3%BCthling_Xenophon_Erinnerungen_001.jpg",
 "Metaphysics (Aristotle)":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Meta-moerbeke_jpeg031-part.jpg/330px-Meta-moerbeke_jpeg031-part.jpg",
 "Nicomachean Ethics":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Aristotelis_De_Moribus_ad_Nicomachum.jpg/330px-Aristotelis_De_Moribus_ad_Nicomachum.jpg",
 "Nineteen Eighty-Four":"https://upload.wikimedia.org/wikipedia/commons/5/51/1984_first_edition_cover.jpg",
 "On Liberty":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/On_Liberty_%28first_edition_title_page_via_facsimile%29.jpg/330px-On_Liberty_%28first_edition_title_page_via_facsimile%29.jpg",
 "On the Genealogy of Morality":"https://upload.wikimedia.org/wikipedia/commons/e/e1/Genealogie_der_Moral_cover.gif",
 "Panopticon":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Panopticon.jpg/330px-Panopticon.jpg",
 "Perpetual Peace: A Philosophical Sketch":"https://upload.wikimedia.org/wikipedia/commons/2/2d/Kant_titlepage_1795.jpg",
 "Persian Letters":"https://upload.wikimedia.org/wikipedia/commons/6/63/Lpersanesmarteau.jpg",
 "Phaedo":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Platonos_Phaedon.JPG/330px-Platonos_Phaedon.JPG",
 "Political Liberalism":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Political_Liberalism_by_John_Rawls_%281993_1st_ed.%29.png/330px-Political_Liberalism_by_John_Rawls_%281993_1st_ed.%29.png",
 "Politics as a Vocation":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Max_Weber_-_Politik_als_Beruf_Seite_01.jpg/330px-Max_Weber_-_Politik_als_Beruf_Seite_01.jpg",
 "Pāli Canon":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pali_Canon_Structure.png/330px-Pali_Canon_Structure.png",
 "Raja Yoga (book)":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Raja_Yoga_Vivekananda_title_page.jpg/330px-Raja_Yoga_Vivekananda_title_page.jpg",
 "Reflections on the Revolution in France":"https://upload.wikimedia.org/wikipedia/commons/3/3c/BurkeReflections.jpg",
 "Relativity: The Special and the General Theory":"https://upload.wikimedia.org/wikipedia/commons/f/f9/The_original_1920_English_publication_of_the_paper..jpg",
 "Republic (Plato)":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Politeia_beginning._Codex_Parisinus_graecus_1807.jpg/330px-Politeia_beginning._Codex_Parisinus_graecus_1807.jpg",
 "Science as a Vocation":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Max_Weber_-_Wissenschaft_als_Beruf_-_Seite_01.jpg/330px-Max_Weber_-_Wissenschaft_als_Beruf_-_Seite_01.jpg",
 "Science of Logic":"https://upload.wikimedia.org/wikipedia/commons/5/5c/Wissenshaft_der_logik.jpg",
 "Some Thoughts Concerning Education":"https://upload.wikimedia.org/wikipedia/commons/6/6b/LockeEducation1693.jpg",
 "Spring and Autumn Annals":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Spring_and_Autumn_Annals_annoted.JPG/330px-Spring_and_Autumn_Annals_annoted.JPG",
 "Symposium (Plato)":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Plato_Symposium_papyrus.jpg/330px-Plato_Symposium_papyrus.jpg",
 "Tao Te Ching":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Mawangdui_LaoTsu_Ms2.JPG/330px-Mawangdui_LaoTsu_Ms2.JPG",
 "Tattvartha Sutra":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Tattvarthsutra.jpg/330px-Tattvarthsutra.jpg",
 "The Arctic Home in the Vedas":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Book_Page.jpg/330px-Book_Page.jpg",
 "The Art of War (Machiavelli)":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Art_of_War-1573.jpg/330px-Art_of_War-1573.jpg",
 "The Communist Manifesto":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Communist-manifesto.png/330px-Communist-manifesto.png",
 "The Gay Science":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/FW82.jpg/330px-FW82.jpg",
 "The German Ideology":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/The_German_Ideology_1932_title_page.jpg/330px-The_German_Ideology_1932_title_page.jpg",
 "The Home and the World":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/The_Home_and_the_World_-_cover_page.jpg/330px-The_Home_and_the_World_-_cover_page.jpg",
 "The Kingdom of God Is Within You":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Tolstoi1st.jpg/330px-Tolstoi1st.jpg",
 "The Old Regime and the Revolution":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Alexis_de_Tocqueville_-_L%27Ancien_R%C3%A9gime_et_la_R%C3%A9volution%2C_L%C3%A9vy%2C_1866.djvu/page1-330px-Alexis_de_Tocqueville_-_L%27Ancien_R%C3%A9gime_et_la_R%C3%A9volution%2C_L%C3%A9vy%2C_1866.djvu.jpg",
 "The Phenomenology of Spirit":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Ph%C3%A4nomenologie_des_Geistes.jpg/330px-Ph%C3%A4nomenologie_des_Geistes.jpg",
 "The Plague (novel)":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/La_Peste_book_cover.jpg/330px-La_Peste_book_cover.jpg",
 "The Prince":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Machiavelli_Principe_Cover_Page.jpg/330px-Machiavelli_Principe_Cover_Page.jpg",
 "The Prophet (book)":"https://upload.wikimedia.org/wikipedia/commons/8/8a/The_Prophet_%28Gibran%29.jpg",
 "The Protestant Ethic and the Spirit of Capitalism":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Die_protestantische_Ethik_und_der_%27Geist%27_des_Kapitalismus_original_cover.jpg/330px-Die_protestantische_Ethik_und_der_%27Geist%27_des_Kapitalismus_original_cover.jpg",
 "The Rebel (book)":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/L%27Homme_r%C3%A9volt%C3%A9_%28Albert_Camus%29.jpg/330px-L%27Homme_r%C3%A9volt%C3%A9_%28Albert_Camus%29.jpg",
 "The Social Contract":"https://upload.wikimedia.org/wikipedia/commons/d/db/Social_contract_rousseau_page.jpg",
 "The Spirit of Law":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Montesquieu%2C_De_l%27Esprit_des_loix_%281st_ed%2C_1748%2C_vol_1%2C_title_page%29.jpg/330px-Montesquieu%2C_De_l%27Esprit_des_loix_%281st_ed%2C_1748%2C_vol_1%2C_title_page%29.jpg",
 "The Stranger (Camus novel)":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/L%27%C3%89tranger_-_Albert_Camus.jpg/330px-L%27%C3%89tranger_-_Albert_Camus.jpg",
 "The Subjection of Women":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/The_Subjection_of_Women.jpg/330px-The_Subjection_of_Women.jpg",
 "Thus Spoke Zarathustra":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Also_sprach_Zarathustra._Ein_Buch_f%C3%BCr_Alle_und_Keinen._In_drei_Theilen.jpg/330px-Also_sprach_Zarathustra._Ein_Buch_f%C3%BCr_Alle_und_Keinen._In_drei_Theilen.jpg",
 "Tirukkuṟaḷ":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AF%81%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AE%B3%E0%AF%8D_%E0%AE%A4%E0%AF%86%E0%AE%B3%E0%AE%BF%E0%AE%B5%E0%AF%81.pdf/page1-330px-%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AF%81%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AE%B3%E0%AF%8D_%E0%AE%A4%E0%AF%86%E0%AE%B3%E0%AE%BF%E0%AE%B5%E0%AF%81.pdf.jpg",
 "Tryst with Destiny":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Jawaharlal_Nehru_gives_his_%22tryst_with_destiny%22_speech_at_Parliament_House_in_New_Delhi_in_1947_%2802%29.jpg/330px-Jawaharlal_Nehru_gives_his_%22tryst_with_destiny%22_speech_at_Parliament_House_in_New_Delhi_in_1947_%2802%29.jpg",
 "Two Treatises of Government":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Locke_treatises_of_government_page.jpg/330px-Locke_treatises_of_government_page.jpg",
 "Utilitarianism (book)":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Utilitarism.jpg/330px-Utilitarism.jpg",
 "Walden":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Walden_Thoreau.jpg/330px-Walden_Thoreau.jpg",
 "War and Peace":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Tolstoy_-_War_and_Peace_-_first_edition%2C_1869.jpg/330px-Tolstoy_-_War_and_Peace_-_first_edition%2C_1869.jpg",
 "Young India":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Young_India.pdf/page1-330px-Young_India.pdf.jpg"
};
