/* =====================================================================
   GLOSSARY — the terms of art used in the model paragraphs
   ---------------------------------------------------------------------
   Generated from the idea headings already written in data.js, so a
   concept is explained here in the same words as on its thinker's page.
   A term earns an entry only if it appears in the paragraphs and is used
   there in its technical sense — 'equality', 'autonomy' and 'middle path'
   are deliberately absent, being ordinary English in every place they
   occur. Key is lowercase; t=term, w=whose, i=thinker id, d=definition.
   ===================================================================== */
const GLOSSARY = {
  "ahimsa":{t:"Ahimsa", w:"Mahatma Gandhi", i:"gandhi",
    d:"Non-violence in thought, word and deed. Not the weapon of the weak but 'the mightiest force at the disposal of mankind'."},
  "alienation":{t:"Alienation", w:"Karl Marx", i:"marx",
    d:"Under industrial capitalism the worker is estranged from the product, the process, fellow workers and their own human essence — a powerful lens on modern workplace burnout."},
  "antyodaya":{t:"Antyodaya", w:"Pandit Deendayal Upadhyaya", i:"deendayal",
    d:"'Rise of the last person.' Policy must be judged by its effect on the poorest; the name behind several Indian welfare schemes."},
  "aparigraha":{t:"Aparigraha", w:"Mahavira", i:"mahavira",
    d:"Non-possession. Limiting one's wants is both a spiritual and an ecological discipline; it inspired Gandhi's trusteeship."},
  "banality of evil":{t:"Banality of Evil", w:"Hannah Arendt", i:"arendt",
    d:"Watching Eichmann's trial, she argued the greatest crimes are committed not by fanatics but by ordinary officials who never stop to think about what they are doing. Indispensable for any discussion of bureaucratic complicity."},
  "banking model of education":{t:"Banking Model of Education", w:"Paulo Freire", i:"freire",
    d:"Teachers 'deposit' information into passive students. It produces obedience, not thought, and mirrors oppression."},
  "bounded rationality":{t:"Bounded Rationality", w:"Herbert Simon", i:"simon",
    d:"Real decision-makers have limited information, limited time and limited cognitive capacity; the ideal of full rational choice is a myth."},
  "buddhist economics":{t:"Buddhist Economics", w:"E. F. Schumacher", i:"schumacher",
    d:"The aim of work is not maximum output but the development of character, the overcoming of ego, and the production of necessary goods. Maximum well-being with minimum consumption."},
  "capability approach":{t:"Capability Approach", w:"Amartya Sen", i:"amartya-sen",
    d:"Well-being is not income or utility but 'capabilities': the real freedoms people have to lead lives they value. Basis of the Human Development Index."},
  "constitutional methods":{t:"Constitutional Methods", w:"Gopal Krishna Gokhale", i:"gokhale",
    d:"Persuasion, petition and reasoned argument; his budget speeches in the Imperial Legislative Council were masterpieces of evidence-based critique."},
  "constitutional morality":{t:"Constitutional Morality", w:"Dr. B. R. Ambedkar", i:"ambedkar",
    d:"Constitutional government depends not only on text but on habits of restraint, respect for institutions and acceptance of lawful limits."},
  "dialectic":{t:"Dialectic", w:"G. W. F. Hegel", i:"hegel",
    d:"Progress occurs through conflict: an idea (thesis) provokes its opposite (antithesis) and both are resolved in a higher synthesis. Marx inverted this into materialism."},
  "difference principle":{t:"Difference Principle", w:"John Rawls", i:"rawls",
    d:"Inequalities are justified only if they work to the greatest benefit of the least advantaged. The philosophical charter of affirmative action and targeted welfare."},
  "eightfold path":{t:"Eightfold Path", w:"Gautama Buddha", i:"buddha",
    d:"Right view, intention, speech, action, livelihood, effort, mindfulness and concentration. Note that Right Livelihood makes one's profession a moral question."},
  "entitlement theory":{t:"Entitlement Theory", w:"Robert Nozick", i:"nozick",
    d:"A distribution is just if holdings were justly acquired and justly transferred, regardless of the resulting pattern. Justice is historical, not patterned."},
  "eudaimonia":{t:"Eudaimonia", w:"Aristotle", i:"aristotle",
    d:"The purpose of life is human flourishing, not pleasure or wealth. A good life is an activity of the soul in accordance with virtue."},
  "grammar of anarchy":{t:"Grammar of Anarchy", w:"Dr. B. R. Ambedkar", i:"ambedkar",
    d:"He warned against methods of civil disobedience once constitutional remedies exist, and against hero-worship: 'bhakti in politics is a sure road to degradation and eventual dictatorship.'"},
  "harm principle":{t:"Harm Principle", w:"John Stuart Mill", i:"mill",
    d:"'The only purpose for which power can rightfully be exercised over any member of a civilised community, against his will, is to prevent harm to others.' The limit of state and social coercion."},
  "ideal speech situation":{t:"Ideal Speech Situation", w:"Jürgen Habermas", i:"habermas",
    d:"Debate free of power, deception and manipulation, where only the force of the better argument prevails."},
  "knowledge worker":{t:"Knowledge Worker", w:"Peter Drucker", i:"drucker",
    d:"He coined the term and predicted that productivity of knowledge work would be the central management challenge."},
  "panopticon":{t:"Panopticon", w:"Jeremy Bentham", i:"bentham",
    d:"A prison design of total visibility; later used by Foucault as the metaphor for modern surveillance."},
  "public sphere":{t:"Public Sphere", w:"Jürgen Habermas", i:"habermas",
    d:"The space between state and market where citizens debate common concerns. Its capture by commerce and spin is a crisis for democracy."},
  "sarvodaya":{t:"Sarvodaya", w:"Acharya Vinoba Bhave", i:"vinoba",
    d:"Welfare of all; he was named the first individual Satyagrahi by Gandhi in 1940."},
  "satyagraha":{t:"Satyagraha", w:"Mahatma Gandhi", i:"gandhi",
    d:"'Truth-force' or 'soul-force': resistance to injustice by voluntary self-suffering rather than by injuring the opponent, aiming to convert rather than coerce."},
  "scientific temper":{t:"Scientific Temper", w:"Jawaharlal Nehru", i:"nehru",
    d:"He coined the term: a spirit of inquiry, evidence and willingness to revise belief. Now a Fundamental Duty under Article 51A(h)."},
  "secularism":{t:"Secularism", w:"Jawaharlal Nehru", i:"nehru",
    d:"Not irreligion but equal respect and state neutrality among faiths (sarva dharma sambhava in practice)."},
  "self-actualisation":{t:"Self-Actualisation", w:"Abraham Maslow", i:"maslow",
    d:"Becoming everything one is capable of becoming; the motivation behind excellence in public service beyond salary."},
  "separation of powers":{t:"Separation of Powers", w:"Montesquieu", i:"montesquieu",
    d:"Legislative, executive and judicial functions must lie in different hands, or liberty perishes. The architecture of every modern constitution, including India's."},
  "social comparison theory":{t:"Social Comparison Theory", w:"Leon Festinger", i:"festinger",
    d:"We evaluate our opinions and abilities by comparing ourselves to others, which explains conformity in organisations."},
  "soft despotism":{t:"Soft Despotism", w:"Alexis de Tocqueville", i:"tocqueville",
    d:"A paternal state that keeps citizens comfortable, passive and permanently childlike; a warning about welfare dependency without participation."},
  "swaraj":{t:"Swaraj", w:"Mahatma Gandhi", i:"gandhi",
    d:"Not merely political independence but self-rule: control over one's own mind and desires, and village-level self-government (Gram Swaraj)."},
  "the absurd":{t:"The Absurd", w:"Albert Camus", i:"camus",
    d:"The clash between our hunger for meaning and the universe's silence. Neither suicide nor false hope is the answer; lucid revolt is."},
  "theory x":{t:"Theory X", w:"Douglas McGregor", i:"mcgregor",
    d:"Assumes people dislike work, avoid responsibility and must be coerced and closely supervised. Produces control-heavy, low-trust administration."},
  "theory y":{t:"Theory Y", w:"Douglas McGregor", i:"mcgregor",
    d:"Assumes work is natural, people seek responsibility and exercise self-direction when committed to objectives. Produces participative, delegating administration."},
  "trusteeship":{t:"Trusteeship", w:"Mahatma Gandhi", i:"gandhi",
    d:"The wealthy should hold their surplus as trustees for society. A moral middle path between capitalism and forced expropriation."},
  "tyranny of the majority":{t:"Tyranny of the Majority", w:"John Stuart Mill", i:"mill",
    d:"Social conformity can oppress more thoroughly than any government. Democracy needs protection from itself."},
  "veil of ignorance":{t:"Veil of Ignorance", w:"John Rawls", i:"rawls",
    d:"Choose the principles of justice without knowing your caste, gender, wealth, talent or religion. What you would then accept is genuinely fair. The single most useful device for any UPSC ethics answer on fairness."},
  "zone of indifference":{t:"Zone of Indifference", w:"Chester Barnard", i:"barnard",
    d:"The range of orders a subordinate will accept without question. Effective leaders widen it through trust and legitimacy."},
};

/* Surnames that double as ordinary English. These thinkers are linked
   only when their full name is written out. */
const GLOSS_AMBIGUOUS = ["Mill", "Phule", "Roy", "Sen"];
