/* =====================================================================
   GS-IV — THE CONCEPTS THAT KEEP COMING BACK
   ---------------------------------------------------------------------
   For each syllabus heading, the ideas the paper has actually returned
   to across 2013-2024, ordered by how often. Each carries a plain
   definition built from open reference sources, and the questions that
   asked it. Derived from the questions in gs4pyq.js rather than from a
   reading list, so the order reflects the paper and not a textbook.
     t   : concept
     qs  : question ids in gs4pyq.js that turn on it
     d   : the definition, in plain paragraphs
     src : where the definition comes from
   ===================================================================== */
const GS4_CONCEPTS = {
  "Ethics & Human Interface":[
    { t:"Conscience",
      qs:["Q004", "Q008", "Q017", "Q018", "Q007"],
      d:["Conscience is a person's awareness of the moral principles they themselves hold, the pull to act on them, and the judgement they pass on their own conduct against them. The Stanford Encyclopedia describes it as inward-looking and subjective in a specific sense: it is always knowledge of oneself, not a rule arriving from outside. It behaves less like a neutral observer and more like a judge.",
         "Two phrases recur in the papers and mean different things. The voice of conscience is the pull felt before or during an act, telling a person what they must or must not do. A crisis of conscience is what happens when two things a person holds binding point in opposite directions, or when an official duty requires what conscience forbids.",
         "The examiner's real question is usually about reliability. Conscience is the most binding guide a person has and the least checkable by anyone else, because no one can audit it. That is why it sits last in the sequence of law, rule, code and conscience, and why an answer that treats it as a licence to override the law will be marked down. It is a final check on the rest, not a substitute for them."],
      src:"Stanford Encyclopedia of Philosophy, entry on Conscience" },
    { t:"Ethics, morals, values and law",
      qs:["Q012", "Q015", "Q004", "Q010"],
      d:["These four are asked as a set and are easiest to hold apart by what each answers. Values are what a person or a society treats as worth pursuing: honesty, security, equality. Morals are the standards of right conduct a person actually holds. Ethics is the reasoned examination of those standards, and the codes that examination produces for a role or a profession. Law is the part the state will enforce.",
         "Two relationships matter for the exam. Law is narrower than ethics, because much that is wrong is not illegal and some of what is legal is indefensible. And ethics is a public activity in a way morals need not be, since an ethical position must be defensible with reasons another person can examine, while a moral conviction may simply be held.",
         "The 2015 paper asked for four such distinctions in a single question, including law against ethics and personal against professional ethics. Practise stating each in one sentence with a single Indian example, because the marks are for the distinction and not for the definition."],
      src:"Standard usage in normative ethics; question wording from the 2013 and 2015 papers" },
    { t:"What ethics seeks to promote",
      qs:["Q005", "Q014", "Q011"],
      d:["This is the most literally repeated question in the whole theme. The 2014 paper asked what ethics seeks to promote in human life and why it matters more in public administration. The 2022 paper opened with the same sentence and then asked how ethical values help resolve everyday conflicts. Eight years apart, the same words.",
         "The usable answer is functional rather than lofty. Ethics supplies standards of conduct that people can expect of one another, which makes cooperation possible without supervising every transaction. Where those expectations hold, an agreement can be relied on, a queue works, an office functions and a contract is cheaper to enforce.",
         "In public administration the requirement is stronger for a specific reason. A private actor spends their own resources and bears their own losses; an official spends public money and exercises power over people who cannot walk away. The scope for harm is larger and the person harmed usually has no alternative, which is why the same conduct that is merely poor practice in private is a breach of trust in office."],
      src:"Common to standard public administration texts; the question wording is from the 2014 and 2022 papers" },
    { t:"The individual good and the common good",
      qs:["Q019", "Q010", "Q011"],
      d:["The 2013 paper quoted the proposition that the good of the individual is contained in the good of all, which is the central claim of Gandhi's sarvodaya. The 2017 paper approached it from the other side, quoting the view that without shared moral values neither law nor democratic government nor the market economy will function properly.",
         "Both point at the same structure. Certain goods cannot be secured individually at any price. Clean air, an epidemic contained, a functioning court, a currency people accept, a road that is safe to use: none can be bought by one person for themselves alone.",
         "The market and the law both presuppose a level of honesty they cannot themselves produce. A contract is enforceable only because most people keep contracts without being sued, and a democracy works only because most losers accept results. Where that stock of shared expectation runs out, enforcement costs rise faster than any state can fund."],
      src:"Gandhi on sarvodaya; the 2017 quotation is from the paper itself" },
    { t:"Essence, determinants and consequences",
      qs:["Q005", "Q006", "Q007"],
      d:["This is the syllabus phrase itself and it repays being read as three separate questions. The essence of ethics is what makes an action right or wrong at all. The determinants are what actually shapes a given person's conduct. The consequences are what follows from ethical or unethical action, for the person and for the society.",
         "The determinants are where most answers are thin, and they are concrete: family and upbringing, education, religion and tradition, peer group and workplace culture, law and its enforcement, and the incentives a person faces. An answer that names the incentive structure alongside the moral formation will be stronger than one that names only conscience and upbringing.",
         "The consequences run both ways and the 2020 papers asked for exactly this. Ethical conduct builds the trust that lowers the cost of every transaction; its absence raises enforcement costs, deters investment, and, as one question put it, can poison a nation's spirit."],
      src:"The phrase is from the GS-IV syllabus; determinants list is standard in public administration texts" },
    { t:"Universal values against changing values",
      qs:["Q016", "Q002"],
      d:["The 2013 paper asked whether values change with time and situation or whether some are universal and eternal. The 2024 paper asked the same thing about justice, stating that the just and the unjust are fluid concepts and inviting a test of that claim.",
         "The defensible position is a distinction between the principle and its application. A small number of commitments appear across societies and periods, such as prohibitions on gratuitous cruelty, on betraying those who trust you and on taking what is not yours. What varies enormously is who counts as a person owed these duties, and what a given practice is understood to mean.",
         "That distinction does the work in an answer. Sati and untouchability were defended as custom and are now prohibited, which looks like values changing. It is better read as the principle of human dignity being extended to people previously excluded from it. The commitment held; the boundary of who it covered moved."],
      src:"Descriptive relativism and moral universalism as set out in open philosophy references" },
    { t:"Personal against professional ethics",
      qs:["Q012", "Q015"],
      d:["Personal ethics is what a person holds as an individual. Professional ethics is what a role requires of whoever occupies it, and it binds because the role was accepted rather than because the holder agrees with it.",
         "The two usually coincide and the exam is interested in where they do not. A doctor's personal disapproval of a patient's conduct does not release them from treating the patient. A civil servant's personal view of a policy does not release them from implementing a lawful decision. A lawyer defends a client they privately believe guilty, because the role exists to make the adversarial system work.",
         "The resolution is that professional ethics is narrower and more demanding at once. It sets aside preferences that a private person may indulge, and it supplies a duty the person did not personally choose. Where the conflict becomes genuinely irreconcilable, the honourable route is to record the objection and, if it cannot be discharged, to leave the role rather than to occupy it and not perform it."],
      src:"Standard treatment in professional ethics literature" },
    { t:"Happiness and the good life",
      qs:["Q013", "Q009"],
      d:["The 2014 paper asked whether all human beings aspire to happiness and what happiness means to the candidate. The 2017 paper asked about a crisis of ethical values traced to a narrow perception of the good life. The pair is really one question about what a life is aimed at.",
         "The classical distinction is the useful one. Pleasure is a feeling, and it is by nature temporary and repeatable. Aristotle's eudaimonia is not a feeling at all but a life going well over its whole course, achieved by exercising one's capacities well rather than by accumulating satisfactions.",
         "The narrow perception the 2017 question names is the reduction of the good life to consumption and status. The answer is not that material conditions do not matter, since deprivation makes almost every other good harder to reach. It is that beyond a threshold the further gains are small, while the goods that continue to matter, such as relationships, purpose and self-respect, are not the sort of thing that can be purchased."],
      src:"Aristotle, Nicomachean Ethics, on eudaimonia" },
    { t:"Moral intuition and moral reasoning",
      qs:["Q003"],
      d:["The 2023 paper asked for the difference with examples. Moral intuition is the fast, automatic judgement that something is wrong, arriving before any argument and often without one. Moral reasoning is the slow, deliberate working out of what follows from a principle. Psychologists label these System 1 and System 2.",
         "Jonathan Haidt's social intuitionist model, published in 2001, makes the stronger claim that in most cases the intuition comes first and the reasoning is constructed afterwards to justify a conclusion already reached. On this account reasoning does its real work between people rather than inside one head, when someone has to defend a position to another person.",
         "For an administrator both are needed and each corrects the other. Intuition is fast and is shaped by upbringing and habit, so it can carry inherited prejudice. Reasoning is slow and can be used to rationalise almost anything. The practical rule is to treat a strong intuition as evidence that something needs examining, and never as the examination itself."],
      src:"Haidt, The Emotional Dog and Its Rational Tail (2001); dual-process framing from cognitive psychology" },
    { t:"Dimensions of ethics",
      qs:["Q001"],
      d:["The 2024 paper asked directly how the dimensions of ethics influence human action and shape decisions in professional contexts. The phrase is used two ways and a strong answer says which it is using.",
         "In philosophy the dimensions are four branches. Descriptive ethics asks what people actually believe is right. Normative ethics asks how one ought to act, and divides into consequentialism, deontology and virtue ethics. Meta-ethics asks what moral words mean and whether moral claims can be true. Applied ethics takes these to particular fields such as medicine, business or administration.",
         "In administrative usage the dimensions are the arenas in which conduct is judged: personal, professional, organisational, social and environmental. Both readings are legitimate. The examiner wants the candidate to show that ethics is not a single rule but a set of distinct questions, and that a professional decision usually engages several of them at once."],
      src:"Branches of ethics as set out in the Internet Encyclopedia of Philosophy and standard open references" },
    { t:"Discrimination and preferential treatment",
      qs:["Q012"],
      d:["Asked as one of four distinctions in 2015, and easy to get wrong by treating both as departures from equal treatment. Both are departures; the difference is in ground and purpose.",
         "Discrimination distinguishes between people on a ground that is irrelevant to the matter at hand, such as caste in a hiring decision or gender in a promotion, and its effect is to entrench an existing disadvantage. Preferential treatment distinguishes on a ground that is relevant precisely because of a history of exclusion, and its purpose is to reduce that disadvantage.",
         "The Indian constitutional position turns on this distinction. Article 15(1) prohibits discrimination on grounds of religion, race, caste, sex or place of birth, while Article 15(4) and Article 16(4) permit special provision for backward classes. The same act of treating two people differently is prohibited under one and authorised under the other, and what separates them is whether the ground is relevant and whether the effect is to entrench disadvantage or to remedy it."],
      src:"Constitution of India, Articles 15 and 16" },
  ],
  "Human Values":[
    { t:"Social capital and trust",
      qs:["Q020", "Q024"],
      d:["Two questions ask this from opposite ends. The 2023 paper asked what social capital is and how it improves quality of life and governance. The 2014 paper asked about a society facing a trust deficit and how a civil servant becomes trustworthy.",
         "Robert Putnam defined social capital as those features of social organisation, such as trust, norms and networks, that improve the efficiency of a society by making coordinated action possible. The OECD puts it as networks together with shared norms and understandings that make cooperation easier within or between groups.",
         "Three forms are usually distinguished. Bonding capital is the tie among people already alike, such as family, caste or neighbourhood, and it is good for getting by. Bridging capital connects groups that would not ordinarily meet, and it is what allows getting ahead. Linking capital, a World Bank addition, connects people to institutions above them in the power hierarchy, which is what determines whether a citizen can actually reach an official.",
         "The governance payoff is concrete. Where trust is high, compliance is voluntary, information reaches officials, and schemes need less policing. Where it is low, every interaction needs verification, which is slow and expensive. Note the honest complication: strong bonding capital without bridging capital produces cohesive groups that exclude outsiders, so more social capital is not automatically better."],
      src:"Putnam, Bowling Alone; OECD definition; World Bank on linking social capital" },
    { t:"Education and the inculcation of values",
      qs:["Q021"],
      d:["The 2020 paper asked for a critical examination of the role of education in inculcating justice, equality and non-discrimination, using the National Education Policy 2020 as the occasion. The word critical is doing work: the question expects both the case and its limits.",
         "The mechanism is not primarily the syllabus. Values are transmitted by what a school does rather than by what it teaches: whether children of different backgrounds sit together and eat together, whether a teacher's attention is distributed evenly, whether rules apply to the influential child as they do to others. A moral science period alongside a segregated playground teaches the playground.",
         "The critical half is that schooling reproduces existing structure at least as often as it changes it. Where school choice tracks income and caste, the system can deliver the curriculum on equality while demonstrating its opposite. This is why the mid-day meal and common-school arguments have always been about contact rather than nutrition or cost alone."],
      src:"National Education Policy 2020; the question wording is from the 2020 paper" },
    { t:"Social values against economic values",
      qs:["Q022"],
      d:["The 2015 paper asked whether social values are more important than economic values, in the context of inclusive national growth. Framing it as a ranking is the trap; the better answer examines what each is for.",
         "Economic values concern efficiency, output and the use of scarce resources. Social values concern how people stand in relation to one another: dignity, fairness, solidarity, obligation. They are not rivals so much as answers to different questions, and the disagreement is about which one settles a case when they conflict.",
         "The concrete cases are where the marks are. A project that raises output while displacing a community, a technology that raises productivity while eliminating the work of those least able to retrain, growth that lifts the average while widening the spread. In each, the economic calculation is complete and still does not settle the matter, because it has no way to register who bore the cost. Inclusive growth is the attempt to make the two answer the same question."],
      src:"The question wording is from the 2015 paper; inclusive growth as used in Indian planning documents" },
    { t:"Patriotism in everyday civil life",
      qs:["Q023"],
      d:["The 2014 paper contrasted patriotism in the defence services, where it can demand the readiness to die, with what it implies in ordinary civil life. The question is asking the candidate to translate a virtue out of its most dramatic form.",
         "In civil life the content is unglamorous and specific: paying tax that is due, obeying rules when no one is watching, refusing to pay or take a bribe, protecting public property, and doing a public job properly on days when nobody is checking. Each is a small transfer from private convenience to common benefit, which is the same structure as the soldier's sacrifice at a far lower cost.",
         "The distinction worth drawing is between patriotism and its counterfeits. Patriotism is a commitment to the country's people and their well-being, and it is therefore compatible with sharp criticism of the government, since wanting a thing to be better is a form of caring about it. Chauvinism substitutes hostility to outsiders for any obligation to insiders, and display substitutes the visible gesture for the unobserved duty."],
      src:"The question wording is from the 2014 paper" },
  ],
};
