/* =====================================================================
   GS PAPER IV — PREVIOUS YEAR QUESTIONS, 2013 to 2024
   ---------------------------------------------------------------------
   220 questions from the twelve papers since Ethics was introduced,
   grouped by the fourteen themes of the compilation and mapped onto the
   syllabus headings in app.js. A theme may map to more than one heading:
   T6 sits under both moral-thinker headings because a third of its
   questions name no thinker and several name an Indian and a world
   thinker together. Every Section B question is also listed under Case
   Studies. Fields: id, y=year, sec=A theory or B case study, m=marks,
   th=theme code, f=focus tag, q=question.
   ===================================================================== */
const GS4_THEMES = [
  { c:"T1", t:"Ethics and Human Interface: Essence, Determinants and Consequences",
    n:19, a:19, b:0,
    maps:["Ethics & Human Interface"] },
  { c:"T2", t:"Human Values: Role of Family, Society and Educational Institutions",
    n:5, a:5, b:0,
    maps:["Human Values"] },
  { c:"T3", t:"Attitude: Content, Structure, Function and Persuasion",
    n:6, a:6, b:0,
    maps:["Attitude"] },
  { c:"T4", t:"Aptitude and Foundational Values for Civil Service",
    n:17, a:14, b:3,
    maps:["Aptitude & Foundational Values for Civil Service"] },
  { c:"T5", t:"Emotional Intelligence",
    n:8, a:8, b:0,
    maps:["Emotional Intelligence"] },
  { c:"T6", t:"Contributions of Moral Thinkers and Philosophers",
    n:33, a:33, b:0,
    maps:["Moral Thinkers & Philosophers of India", "Moral Thinkers & Philosophers of the World"] },
  { c:"T7", t:"Public / Civil Service Values and Ethics in Public Administration",
    n:22, a:13, b:9,
    maps:["Public / Civil Service Values & Ethics in Public Administration"] },
  { c:"T8", t:"Probity in Governance: Transparency, RTI, Codes and Service Delivery",
    n:24, a:17, b:7,
    maps:["Probity in Governance"] },
  { c:"T9", t:"Corruption, Whistleblowing and Conflict of Interest",
    n:20, a:9, b:11,
    maps:["Corruption, Whistleblowing & Conflict of Interest"] },
  { c:"T10", t:"Corporate Governance, Business and Workplace Ethics",
    n:14, a:2, b:12,
    maps:["Corporate Governance & Workplace Ethics"] },
  { c:"T11", t:"Ethics in International Relations and Funding",
    n:7, a:6, b:1,
    maps:["Accountability & Ethical Governance"] },
  { c:"T12", t:"Ethics in Science, Technology, Medicine and Media",
    n:18, a:5, b:13,
    maps:["Ethics in Science, Technology & Media"] },
  { c:"T13", t:"Environmental and Development Ethics",
    n:15, a:6, b:9,
    maps:["Environmental & Development Ethics"] },
  { c:"T14", t:"Social Justice, Gender and the Weaker Sections",
    n:12, a:3, b:9,
    maps:["Social Justice, Gender & the Weaker Sections"] },
];

const GS4_PYQ = [
  { id:"Q001", y:2024, sec:"A", m:"12.5 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"Ethics encompasses several key dimensions that are crucial in guiding individuals and organizations towards morally responsible behaviour. Explain how these dimensions influence human actions and shape ethical decision-making in professional contexts." },
  { id:"Q002", y:2024, sec:"A", m:"12.5 marks", th:"T1",
    f:"Ethics and Justice",
    q:"Justice is always contextual; the just and the unjust are fluid concepts. Test this statement with suitable examples." },
  { id:"Q003", y:2023, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"Differentiate 'moral intuition' from 'moral reasoning' with suitable examples." },
  { id:"Q004", y:2023, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Conscience",
    q:"Is conscience a more reliable guide than laws, rules, and regulations in ethical decision-making? Discuss." },
  { id:"Q005", y:2022, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"It is believed that adherence to ethics in human actions would ensure in smooth functioning of an organization / system. If so, what does ethics seek to promote in human life? How do ethical values assist in the resolution of conflicts faced by him in his day-to-day functioning?" },
  { id:"Q006", y:2020, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and National Power / Values",
    q:"Discuss the role of ethics and values in enhancing the following three major components of Comprehensive National Power (CNP) viz. human capital, soft power (culture and policies), and social harmony." },
  { id:"Q007", y:2020, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface / Values",
    q:"Hatred is destructive of a person's wisdom and conscience that can poison a nation's spirit. Do you agree with this view? Justify your answer with suitable examples." },
  { id:"Q008", y:2019, sec:"A", m:"10 marks", th:"T1",
    f:"Conscience / Ethics",
    q:"What is meant by 'crisis of conscience'? How does it manifest itself in the public domain?" },
  { id:"Q009", y:2017, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"'The crisis of ethical values in modern times is traced to a narrow perception of the good life.' Discuss." },
  { id:"Q010", y:2017, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Society",
    q:"'Without commonly shared and widely entrenched moral values and obligations, neither the law, nor democratic government, nor even the market economy will function properly.' What do you understand by this statement? Explain with illustration in the contemporary times." },
  { id:"Q011", y:2016, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"Explain how ethics contributes to social and human well-being." },
  { id:"Q012", y:2015, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"Differentiate between the following: (i) Law and ethics (ii) Ethical management and management of ethics (iii) Discrimination and preferential treatment (iv) Personal ethics and professional ethics" },
  { id:"Q013", y:2014, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"All human beings aspire for happiness. Do you agree? What does happiness mean to you? Explain with examples." },
  { id:"Q014", y:2014, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"What does ethics seek to promote in human life? Why is it all the more important in Public Administration?" },
  { id:"Q015", y:2013, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Human Interface",
    q:"What do you understand by 'values' and 'ethics'? In what way is it important to be ethical along with being professionally competent?" },
  { id:"Q016", y:2013, sec:"A", m:"10 marks", th:"T1",
    f:"Values / Ethics",
    q:"Some people feel that values keep changing with time and situation, while others strongly believe that there are certain universal and eternal human values. Give your perception in this regard with due justification." },
  { id:"Q017", y:2013, sec:"A", m:"10 marks", th:"T1",
    f:"Conscience / Ethics",
    q:"What do you understand by the term 'voice of conscience'? How do you prepare yourself to heed to the voice of conscience?" },
  { id:"Q018", y:2013, sec:"A", m:"10 marks", th:"T1",
    f:"Conscience / Personal Ethics",
    q:"What is meant by 'crisis of conscience'? Narrate one incident in your life when you were faced with such a crisis and how you resolved the same." },
  { id:"Q019", y:2013, sec:"A", m:"10 marks", th:"T1",
    f:"Ethics and Society",
    q:"'The good of an individual is contained in the good of all.' What do you understand by this statement? How can this principle be implemented in public life?" },
  { id:"Q020", y:2023, sec:"A", m:"10 marks", th:"T2",
    f:"Social Ethics / Governance",
    q:"Explain social capital and how it enhances the quality of life and good governance." },
  { id:"Q021", y:2020, sec:"A", m:"10 marks", th:"T2",
    f:"Education Ethics / NEP 2020",
    q:"New Education Policy 2020 is considered as a step forward for transformative India. Critically examine the role of education in inculcating ethical values of justice, equality, and non-discrimination in the youth." },
  { id:"Q022", y:2015, sec:"A", m:"10 marks", th:"T2",
    f:"Social Ethics / Development",
    q:"'Social values are more important than economic values.' Discuss this statement with examples in the context of inclusive national growth." },
  { id:"Q023", y:2014, sec:"A", m:"10 marks", th:"T2",
    f:"Values / Patriotism",
    q:"In defence services, 'patriotism' demands readiness to lay down one's life in the service of the nation. According to you, what does patriotism imply in everyday civil life? Explain with suitable examples." },
  { id:"Q024", y:2014, sec:"A", m:"10 marks", th:"T2",
    f:"Trust / Social Ethics",
    q:"Society faces a trust-deficit today. What are its consequences? How can you, as a civil servant, become trustworthy?" },
  { id:"Q025", y:2022, sec:"A", m:"10 marks", th:"T3",
    f:"Civil Service Values / Attitude",
    q:"The Rules and Regulations provided to all the civil servants are same, yet there is difference in the performance. Positive-minded officers are able to interpret the Rules and Regulations in favour of the case and achieve success, whereas negative-minded officers are unable to achieve goals by interpreting the same Rules and Regulations against the case. Discuss with illustrations." },
  { id:"Q026", y:2021, sec:"A", m:"10 marks", th:"T3",
    f:"Attitude",
    q:"Attitude is an important component that goes as input in the development of human beings. How to build a suitable attitude needed for a public servant?" },
  { id:"Q027", y:2016, sec:"A", m:"10 marks", th:"T3",
    f:"Attitude / Social Ethics",
    q:"Attitudes towards life, work, people, and society are shaped unconsciously by family and social surroundings. Many unconsciously acquired attitudes are undesirable in modern democratic society. (a) Discuss such undesirable attitudes prevalent in today's educated Indians. (b) How can such attitudes be changed and socio-ethical values necessary in public services be cultivated in aspiring and serving civil servants?" },
  { id:"Q028", y:2016, sec:"A", m:"10 marks", th:"T3",
    f:"Social Ethics / Governance",
    q:"Discuss how social influence and persuasion can contribute to the success of the Swachh Bharat Abhiyan." },
  { id:"Q029", y:2015, sec:"A", m:"10 marks", th:"T3",
    f:"Civil Service Values / Attitude",
    q:"(a) Distinguish between 'democratic attitudes' and 'bureaucratic attitudes' of public servants. Discuss the merits and demerits of each. (b) Can these attitudes be balanced for better administration and development?" },
  { id:"Q030", y:2014, sec:"A", m:"10 marks", th:"T3",
    f:"Attitude / Social Ethics",
    q:"What factors affect attitude formation toward social problems? How can we as a society address the contrasting attitudes about the caste system which prevail in our society?" },
  { id:"Q031", y:2021, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Aptitude",
    q:"Identify five ethical traits on which one can plot the performance of a civil servant. Justify their inclusion in the matrix." },
  { id:"Q032", y:2021, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values",
    q:"Identify ten essential values that are needed to be an effective public servant. Describe the ways and means to prevent non-ethical behaviour in the public servants." },
  { id:"Q033", y:2021, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Problem Solving",
    q:"Besides domain knowledge, a public official needs innovativeness and creativity of a high order as well, while resolving ethical dilemmas. Discuss with a suitable example." },
  { id:"Q034", y:2021, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Impartiality",
    q:"Should impartial and being non-partisan be considered indispensable qualities to make a successful civil servant? Discuss with illustrations." },
  { id:"Q035", y:2021, sec:"A", m:"10 marks", th:"T4",
    f:"Integrity",
    q:"'Integrity is a value that empowers the human being.' Justify with illustration." },
  { id:"Q036", y:2018, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Aptitude",
    q:"State the three basic values, universal in nature, in the context of civil services and bring out their importance." },
  { id:"Q037", y:2017, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Aptitude",
    q:"Examine the relevance of the following in the context of civil service: (a) Transparency (b) Accountability (c) Fairness and justice (d) Courage of conviction (e) Spirit of service" },
  { id:"Q038", y:2017, sec:"A", m:"10 marks", th:"T4",
    f:"Integrity",
    q:"'One of the tests of integrity is complete refusal to be compromised.' Explain with reference to a real life example." },
  { id:"Q039", y:2016, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values",
    q:"Why should impartiality and non-partisanship be considered foundational values in public services, especially in the present socio-political context? Illustrate with examples." },
  { id:"Q040", y:2015, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Aptitude",
    q:"How do the virtues of trustworthiness and fortitude get manifested in public service? Explain with examples." },
  { id:"Q041", y:2014, sec:"A", m:"10 marks", th:"T4",
    f:"Integrity / Knowledge",
    q:"'Integrity without knowledge is weak and useless; knowledge without integrity is dangerous and dreadful.' What do you understand by this statement? Explain with suitable examples." },
  { id:"Q042", y:2014, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Ethical Competence",
    q:"Public servants handling power and public funds have wide societal impact. What steps have you personally taken to improve your ethical competence to handle this power and responsibility in public service?" },
  { id:"Q043", y:2013, sec:"A", m:"15 marks", th:"T4",
    f:"Civil Service Values / Aptitude",
    q:"What do you understand by the following terms in the context of public service? (i) Integrity (ii) Perseverance (iii) Spirit of service (iv) Commitment (v) Courage of conviction" },
  { id:"Q044", y:2013, sec:"A", m:"10 marks", th:"T4",
    f:"Civil Service Values / Aptitude",
    q:"Indicate two more attributes which you consider important for public service. Justify your answer." },
  { id:"Q045", y:2021, sec:"B", m:"20 marks", th:"T4",
    f:"Academic Ethics / Political Pressure / Integrity",
    q:"You are the Vice Principal of a reputed college. You discover that students and a senior lecturer are indulging in malpractice during exams. The students are children of influential people — a politician and a businessman. The management pressures you to settle it quietly, hinting your promotion to Principal is at stake. Student unions protest outside. [Sub-questions: (a) Discuss ethical issues involved. (b) Critically examine options; recommend approach with reasoning.]" },
  { id:"Q046", y:2017, sec:"B", m:"20 marks", th:"T4",
    f:"Civil Service Ethics / Integrity",
    q:"You are an honest and responsible civil servant. Examine the following four statements with their merits and demerits: (a) Adhering to ethical conduct causes personal difficulties and career setbacks, whereas unfair practices help reach career goals. (b) When many people adopt unfair means, a small minority with ethical inclinations makes no difference. (c) Sticking to ethical means is detrimental to larger developmental goals. (d) While avoiding large unethical practices, giving and accepting small gifts makes the system more efficient." },
  { id:"Q047", y:2014, sec:"B", m:"20 marks", th:"T4",
    f:"Civil Service Ethics / Integrity",
    q:"Your friend, a civil servant, expresses the following views: (i) Ethical principles cause personal difficulties and career setbacks while unfair practices help reach career goals. (ii) Small minority efforts for ethics make no difference. (iii) Ethical considerations hamper developmental objectives. (iv) Small gratifications improve efficiency. Address each view with its merits and demerits." },
  { id:"Q048", y:2023, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"Does emotional quotient (EQ) matter more than intelligence quotient (IQ) for a person in position of power? Discuss with suitable examples." },
  { id:"Q049", y:2022, sec:"A", m:"10 marks", th:"T5",
    f:"Civil Service Values / Emotional Intelligence",
    q:"Apart from intellectual competency and moral qualities, empathy and compassion are some of the other vital attributes that facilitate the civil servants to be more competent in tackling the crucial issues or taking critical decisions. Explain with suitable illustrations." },
  { id:"Q050", y:2021, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"In case of a crisis of conscience, does emotional intelligence help to overcome the same without compromising the ethical and moral stand that you are likely to follow? Critically examine." },
  { id:"Q051", y:2020, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"Identify the major components of emotional maturity. Whether this can be developed in a person? Substantiate your view." },
  { id:"Q052", y:2019, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"Emotional Intelligence is the ability to make your emotions work for you instead of against you. Do you agree with this view? Discuss." },
  { id:"Q053", y:2017, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"How will you apply emotional intelligence in administrative practices?" },
  { id:"Q054", y:2016, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"Anger is a harmful negative emotion injurious to both personal and work life. (a) Discuss how it leads to negative emotions and undesirable behaviours. (b) How can it be managed and controlled?" },
  { id:"Q055", y:2013, sec:"A", m:"10 marks", th:"T5",
    f:"Emotional Intelligence",
    q:"What is 'emotional intelligence' and how can it be developed in people? How does it help an individual in taking ethical decisions?" },
  { id:"Q056", y:2024, sec:"A", m:"12.5 marks", th:"T6",
    f:"Moral Thinkers / Attitude",
    q:"What does the following quotation mean to you? 'We are what our thinking has made us; so take care about what you think. Words are secondary. Thoughts live; they travel far.' — Swami Vivekananda" },
  { id:"Q057", y:2024, sec:"A", m:"12.5 marks", th:"T6",
    f:"Moral Thinkers / Aptitude",
    q:"What does the following quotation mean to you? 'No Power can be won without the help of God and the people. Strength does not come from physical capacity. It comes from an indomitable will and faith.' — Sardar Vallabhbhai Patel" },
  { id:"Q058", y:2024, sec:"A", m:"12.5 marks", th:"T6",
    f:"Moral Thinkers / Ethical Theory",
    q:"What does the following quotation mean to you? 'Act in such a way that you treat humanity, whether in your own person or in the person of any other, never merely as a means to an end, but always at the same time as an end.' — Immanuel Kant" },
  { id:"Q059", y:2023, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Attitude",
    q:"What does the following quotation mean to you in the present context? 'One must always maintain one's connection to the past and yet ceaselessly pull away from it.' — Simone de Beauvoir [or the Gandhi quotation on kindness and prayer printed in the 2023 paper]" },
  { id:"Q060", y:2023, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Gender",
    q:"What does the following quotation mean to you? (Nehru quotation on the importance of women's awakening for national progress)" },
  { id:"Q061", y:2023, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'Our duty is to encourage every one in his struggle to live up to his own highest ideal, and strive at the same time to make the ideal as near as possible to the truth.' — Swami Vivekananda" },
  { id:"Q062", y:2023, sec:"A", m:"10 marks", th:"T6",
    f:"Indian Moral Thinkers",
    q:"What were the major teachings of Guru Nanak? Explain their relevance in the contemporary world." },
  { id:"Q063", y:2022, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Quotations",
    q:"What does each of the following quotations mean to you? (a) 'Ethics is knowing the difference between what you have the right to do and what is right to do.' — Potter Stewart (b) 'If a country is to be corruption free and become a nation of beautiful minds, I strongly feel that there are three key societal members who can make a difference. They are father, mother and teacher.' — A.P.J. Abdul Kalam (c) 'Judge your success by what you had to give up in order to get it.' — Dalai Lama" },
  { id:"Q064", y:2021, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Attitude",
    q:"What does the following quotation mean to you in the present context? 'The simplest acts of kindness are by far more powerful than a thousand heads bowing in prayer.' — Mahatma Gandhi [or the Swami Vivekananda perseverance quote from the 2021 paper]" },
  { id:"Q065", y:2021, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'Peace does not mean an absence of conflicts; differences will always be there. Peace means solving these differences through peaceful means; through dialogue, education, knowledge; and through humane ways.' — Dalai Lama" },
  { id:"Q066", y:2021, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'The weak can never forgive. Forgiveness is the attribute of the strong.' [Erik Erikson quote on interdependence / the Erikson quotation printed in 2021 paper]" },
  { id:"Q067", y:2020, sec:"A", m:"10 marks", th:"T6",
    f:"Indian Moral Thinkers",
    q:"What teachings of Buddha are most relevant today and why? Discuss." },
  { id:"Q068", y:2020, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'Condemn none: if you can stretch out a helping hand, do so. If not, fold your hands, bless your brothers, and let them go their own way.' — Swami Vivekanand" },
  { id:"Q069", y:2020, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'The best way to find yourself is to lose yourself in the service of others.' — Mahatma Gandhi" },
  { id:"Q070", y:2020, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'It is not enough to have a good mind; the main thing is to use it well.' — Descartes [or the Socrates quote on morality's rational foundations printed in the 2020 paper]" },
  { id:"Q071", y:2019, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'An unexamined life is not worth living.' — Socrates" },
  { id:"Q072", y:2019, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'A man is but the product of his thoughts. What he thinks he becomes.' — M.K. Gandhi" },
  { id:"Q073", y:2019, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'Where there is righteousness in the heart, there is beauty in the character. When there is beauty in the character, there is harmony in the home. When there is harmony in the home, there is order in the nation. When there is order in the nation, there is peace in the world.' — A.P.J. Abdul Kalam" },
  { id:"Q074", y:2018, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Civil Service Values",
    q:"Analyse the statements of Warren Buffett that 'In looking for people to hire, you look for three qualities: integrity, intelligence and energy. And if they don't have the first, the other two will kill you.' What are the implications of the statement for conduct of civil services?" },
  { id:"Q075", y:2018, sec:"A", m:"10 marks", th:"T6",
    f:"Ethical Theory / Consequentialism / Deontology",
    q:"Compare and contrast the following views on the morality of actions: (a) The morality of an action is determined by the results or consequences of the action. (b) The morality of an action is determined by the intention behind it, not by results." },
  { id:"Q076", y:2018, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'If I am not for myself, who will be for me? But if I am only for myself, what am I? If not now, when?' — Abraham Lincoln [or the Lincoln government policy / evil-good quote from 2018 paper]" },
  { id:"Q077", y:2018, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you? 'Anger and intolerance are the enemies of correct understanding.' — Mahatma Gandhi" },
  { id:"Q078", y:2018, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Indian Ethics",
    q:"What does the following quotation mean to you? 'If falsehood like a bit of thread is tossed aside, its harm is less; if swallowed, it burns like fire.' — Tirukkural" },
  { id:"Q079", y:2017, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Leadership",
    q:"What does the following quotation mean to you? 'Great ambition is the passion of a great character. Those endowed with it may perform very good or very bad acts. All depends on the principles which direct them.' — Napoleon Bonaparte. Stating examples mention the rulers (i) who have harmed society and country, (ii) who worked for the development of society and country." },
  { id:"Q080", y:2017, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Corruption",
    q:"What does the following quotation mean to you? 'If a country is to be corruption free and become a nation of beautiful minds, I strongly feel that there are three key societal members who can make a difference. They are father, mother and teacher.' — A.P.J. Abdul Kalam. Analyse." },
  { id:"Q081", y:2016, sec:"A", m:"10 marks", th:"T6",
    f:"Administrative Ethics / Weber",
    q:"'Max Weber said that it is not wise to apply to public administration the sort of moral and ethical norms we apply to matters of personal conscience. It is important to realize that the state bureaucracy might possess its own independent bureaucratic morality.' Critically analyse this statement." },
  { id:"Q082", y:2016, sec:"A", m:"10 marks", th:"T6",
    f:"Indian Ethics / Kautilya / Probity",
    q:"(a) 'Corruption causes misuse of government treasury, administrative inefficiency and obstruction in national development.' Discuss Kautilya's views on corruption in light of this statement. (b) Discuss the Public Services Code as recommended by the 2nd Administrative Reforms Commission." },
  { id:"Q083", y:2016, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Social Justice",
    q:"(a) Analyse John Rawls's concept of social justice in the Indian context. (b) Discuss Mahatma Gandhi's concept of seven social sins." },
  { id:"Q084", y:2015, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you in the present context? 'The weak can never forgive; forgiveness is the attribute of strong.' — Mahatma Gandhi" },
  { id:"Q085", y:2015, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers",
    q:"What does the following quotation mean to you in the present context? 'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.' — Plato" },
  { id:"Q086", y:2014, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Kant / Human Dignity",
    q:"Human beings should always be treated as 'ends' in themselves and never as 'means'. Explain the implications of this statement in the modern techno-economic society." },
  { id:"Q087", y:2014, sec:"A", m:"10 marks", th:"T6",
    f:"Moral Thinkers / Personal Ethics",
    q:"Which eminent ethical personality has inspired you the most and why? Describe how you applied the teachings of that eminent personality in facing a difficult situation in your life." },
  { id:"Q088", y:2013, sec:"A", m:"30 marks", th:"T6",
    f:"Moral Thinkers",
    q:"Given below are three quotations of great moral thinkers / philosophers. For each of these quotations, bring out what it means to you in the present context: (a) 'There is enough on this earth for every one's need but not for every one's greed.' — Mahatma Gandhi. (b) 'Nearly all men can withstand adversity, but if you want to test a man's character, give him power.' — Abraham Lincoln. (c) 'I count him braver who overcomes his desires than him who overcomes his enemies.' — Aristotle" },
  { id:"Q089", y:2024, sec:"A", m:"12.5 marks", th:"T7",
    f:"Civil Service Values",
    q:"In the performance of their duties, civil servants should always give importance to substance over form. Illustrate with suitable examples." },
  { id:"Q090", y:2024, sec:"A", m:"12.5 marks", th:"T7",
    f:"Legal Ethics / Justice",
    q:"The Bharatiya Nyaya Sanhita is founded on the principle that the foundation of justice is 'Justice, Equality and Impartiality'. How does this reflect a paradigm shift from a punishment doctrine to a justice-based approach in the judicial system?" },
  { id:"Q091", y:2020, sec:"A", m:"10 marks", th:"T7",
    f:"Civil Service Values / Governance",
    q:"'The will to power combined with rational and moral duties of civil service to society is a recipe for good governance.' Do you agree? Discuss." },
  { id:"Q092", y:2020, sec:"A", m:"10 marks", th:"T7",
    f:"Ethics and Law",
    q:"Distinguish between laws and rules. Discuss the role of ethics in formulating them." },
  { id:"Q093", y:2019, sec:"A", m:"10 marks", th:"T7",
    f:"Civil Service Values",
    q:"What do you understand by the term 'public servant'? Reflect on the expected role of a public servant." },
  { id:"Q094", y:2019, sec:"A", m:"10 marks", th:"T7",
    f:"Constitutional Ethics",
    q:"What is meant by the term 'constitutional morality'? How does one uphold constitutional morality?" },
  { id:"Q095", y:2018, sec:"A", m:"10 marks", th:"T7",
    f:"Administrative Ethics / Law and Morality",
    q:"Examine the statement 'In doing a good thing, everything is permitted which is not prohibited expressly or by clear implication.' Do you agree? Justify your answer with examples in the context of a public servant discharging his / her duties." },
  { id:"Q096", y:2018, sec:"A", m:"10 marks", th:"T7",
    f:"Administrative Ethics / Ethical Dilemmas",
    q:"Explain the process of resolving ethical dilemmas in Public Administration." },
  { id:"Q097", y:2017, sec:"A", m:"10 marks", th:"T7",
    f:"Political Ethics / Values",
    q:"Young people with ethical conduct are not willing to come forward to join active politics. Suggest steps to motivate them to come forward." },
  { id:"Q098", y:2017, sec:"A", m:"10 marks", th:"T7",
    f:"Civil Service Values / Discipline",
    q:"'Discipline generally implies following the order and subordination. However, it may be counter-productive for the organisation.' Discuss." },
  { id:"Q099", y:2016, sec:"A", m:"10 marks", th:"T7",
    f:"Ethics and Law",
    q:"Law and ethics are tools for controlling human conduct conducive to civilized social existence. (a) Discuss how they achieve this objective. (b) Discuss with examples how the two differ in their approaches." },
  { id:"Q100", y:2015, sec:"A", m:"10 marks", th:"T7",
    f:"Ethics and Law / Civil Service",
    q:"'A mere compliance with law is not enough, the public servant also has to have a well developed sensibility to ethical issues for effective discharge of duties.' Provide examples where (i) an act is ethically right but not legally, and (ii) an act is legally right but not ethically." },
  { id:"Q101", y:2013, sec:"A", m:"10 marks", th:"T7",
    f:"Political Ethics",
    q:"It is often said that 'politics' and 'ethics' do not go together. What is your opinion in this regard? Justify your answer with illustrations." },
  { id:"Q102", y:2024, sec:"B", m:"25 marks", th:"T7",
    f:"Police Ethics / Security / Social Ethics",
    q:"Raman, a senior IPS officer posted as the Commissioner of Police in a metropolitan city, discovers that a global terrorist organization is targeting unemployed graduates from specific communities through social media and recruiting them into their ranks. [Sub-questions: (a) What are the options available to Raman to deal with this situation? (b) What institutional measures would you suggest to strengthen the police organisation in tackling this problem? (c) How can intelligence gathering be enhanced to prevent further infiltration?]" },
  { id:"Q103", y:2024, sec:"B", m:"25 marks", th:"T7",
    f:"Police Ethics / Tribal Rights / Law Enforcement",
    q:"SP Rohit receives credible intelligence that some hardcore Naxalites are hiding in a village in his jurisdiction. Before he could act, a group of about 500 tribal women surround the police station demanding the release of the Naxalites. [Sub-questions: (a) What options are available to SP Rohit? (b) What are the ethical dilemmas involved? (c) What, according to you, would be the most appropriate course of action, and why? (d) How would you handle gender-sensitive dimensions of dealing with the protesters?]" },
  { id:"Q104", y:2022, sec:"B", m:"20 marks", th:"T7",
    f:"Civil Service Values / Family vs Duty / Security",
    q:"Ramesh is State Civil Services Officer who got the opportunity of getting posted to the capital of a border State after rendering 20 years of service. Ramesh's mother has recently been detected cancer and has been admitted in the leading cancer hospital of the city. Meanwhile, the Government of the neighboring country started pushing a large number of illegal migrants into Ramesh's State. This has created a serious law-and-order problem. [Sub-questions: (a) What are the options available to Ramesh as the Director of the Home Department of the bordering State? (b) What option should Ramesh adopt and why? (c) Critically evaluate each of the options. (d) What are the ethical dilemmas being faced by Ramesh? (e) What policy measures would you suggest to combat the menace of infiltration of illegal migrants from the neighbouring country?]" },
  { id:"Q105", y:2021, sec:"B", m:"20 marks", th:"T7",
    f:"Corruption / Police Ethics / Administrative Courage",
    q:"Sunil is an IAS officer serving in a tribal district. He discovers that sand is being illegally mined from river banks. The contractor is politically connected. Sunil's predecessors were pressured into transferring out, and one was murdered. His subordinates are compromised and his family is threatened by musclemen. [Sub-questions: (a) Identify the options available to Sunil. (b) Critically evaluate each option. (c) Recommend the most appropriate approach with justification.]" },
  { id:"Q106", y:2019, sec:"B", m:"20 marks", th:"T7",
    f:"Disaster Management / Leadership / Civil Service Values",
    q:"You are heading a rescue team during a natural calamity. Disrupted logistics, homeless displaced persons, public anger over delayed relief, and a team member severely injured by an irate mob force you to consider calling off the operation. [Sub-questions: (a) What will be your response? (b) Examine the qualities of a public servant needed to manage such a situation.]" },
  { id:"Q107", y:2019, sec:"B", m:"20 marks", th:"T7",
    f:"Police Ethics / Drug Menace / Law Enforcement",
    q:"A woman police officer is appointed Superintendent of Police in a frontier district facing a severe narcotics crisis — drug trafficking, money laundering, poppy farming, arms smuggling, education disruption, and alleged political-police patronage of drug mafia. [Sub- questions: (a) Identify the various dimensions of the crisis. (b) Suggest measures to deal with the crisis.]" },
  { id:"Q108", y:2018, sec:"B", m:"20 marks", th:"T7",
    f:"Police Ethics / Holistic Governance / Law Enforcement",
    q:"You are appointed Superintendent of Police in a prohibition state with severe illicit distillation problems. Past law-and-order approaches proved ineffective. The district shows economic, industrial, and educational backwardness with poor irrigation and community clashes. Propose a new holistic approach to address both the prohibition enforcement and underlying development issues." },
  { id:"Q109", y:2017, sec:"B", m:"20 marks", th:"T7",
    f:"Ethical Dilemma / Duty vs Personal Obligation",
    q:"You are aspiring to become an IAS officer and have cleared various stages and been selected for the personal interview. On the way to the venue you witness an accident where your relative (mother and child) are badly injured. What would you have done in such a situation? Justify your action." },
  { id:"Q110", y:2015, sec:"B", m:"20 marks", th:"T7",
    f:"Disaster Management / Administrative Ethics / Triage",
    q:"A disaster-prone state experiences cloudbursts causing devastating floods and landslides with high casualties. Over 100,000 pilgrims, tourists, and locals are trapped — including senior citizens, hospital patients, women, children, tourists, ruling party officials, additional chief secretary, and prisoners. As civil services officer, in what rescue order would you prioritize these groups and why? Provide justifications." },
  { id:"Q111", y:2024, sec:"A", m:"12.5 marks", th:"T8",
    f:"Probity / Code of Ethics",
    q:"Propose a suitable model for implementing a code of ethics in public governance, distinguishing it from a code of conduct." },
  { id:"Q112", y:2024, sec:"A", m:"12.5 marks", th:"T8",
    f:"Civil Service Capacity Building",
    q:"Analyse how Mission Karmayogi empowers civil servants in enhancing their productive efficiency and delivering grassroots-level services." },
  { id:"Q113", y:2023, sec:"A", m:"10 marks", th:"T8",
    f:"Probity in Governance",
    q:"'Probity is essential for an effective system of governance and socio-economic development.' Discuss." },
  { id:"Q114", y:2022, sec:"A", m:"10 marks", th:"T8",
    f:"Ethics Terms / Probity / Civil Service",
    q:"Write short notes on the following in 30 words each: (i) Constitutional morality (ii) Conflict of interest (iii) Probity in public life (iv) Challenges of digitalization (v) Devotion to duty" },
  { id:"Q115", y:2022, sec:"A", m:"10 marks", th:"T8",
    f:"Administrative Ethics / Good Governance",
    q:"'Wisdom lies in knowing what to reckon with and what to overlook.' An officer being engrossed with the periphery, ignoring the core issues before him, is not rare in the bureaucracy. Do you agree that such preoccupation of an administrator leads to travesty of justice to the cause of effective service delivery and good governance? Critically evaluate." },
  { id:"Q116", y:2019, sec:"A", m:"10 marks", th:"T8",
    f:"Nolan Principles / Public Life Ethics",
    q:"What are the basic principles of public life? Illustrate any three of these with suitable examples." },
  { id:"Q117", y:2019, sec:"A", m:"10 marks", th:"T8",
    f:"Public Finance Ethics / Probity",
    q:"Effective utilization of public funds is crucial to meet development goals. Critically examine the reasons for under-utilization and mis-utilization of public funds and their implications." },
  { id:"Q118", y:2019, sec:"A", m:"10 marks", th:"T8",
    f:"Citizen Charter / Good Governance",
    q:"Explain the basic principles of the citizens' charter movement and bring out its importance." },
  { id:"Q119", y:2019, sec:"A", m:"10 marks", th:"T8",
    f:"RTI / Transparency / Probity",
    q:"There is a view that the Official Secrets Act is an obstacle to the implementation of Right to Information Act. Do you agree with the view? Discuss." },
  { id:"Q120", y:2019, sec:"A", m:"10 marks", th:"T8",
    f:"Probity in Governance",
    q:"What do you understand by probity in governance? Based on your understanding of the term, suggest measures for ensuring probity in government." },
  { id:"Q121", y:2018, sec:"A", m:"10 marks", th:"T8",
    f:"Ethics / Probity",
    q:"Distinguish between 'Code of ethics' and 'Code of conduct' with suitable examples." },
  { id:"Q122", y:2018, sec:"A", m:"10 marks", th:"T8",
    f:"Civil Service Values / Public Interest",
    q:"What is meant by public interest? What are the principles and procedures to be followed by civil servants in public interest?" },
  { id:"Q123", y:2018, sec:"A", m:"10 marks", th:"T8",
    f:"RTI / Transparency / Probity",
    q:"'The Right to Information Act is not all about citizens' empowerment alone, it essentially redefines the concept of accountability.' Discuss." },
  { id:"Q124", y:2016, sec:"A", m:"10 marks", th:"T8",
    f:"Good Governance",
    q:"What do you understand by the terms 'governance', 'good governance' and 'ethical governance'?" },
  { id:"Q125", y:2015, sec:"A", m:"10 marks", th:"T8",
    f:"Transparency / RTI / Governance",
    q:"Recent developments like the RTI Act, media activism, and judicial activism have enhanced transparency in governance. However, these mechanisms are sometimes misused and officers tend to procrastinate in taking decisions out of fear. Analyse this situation and suggest measures to minimize such negative impacts." },
  { id:"Q126", y:2014, sec:"A", m:"10 marks", th:"T8",
    f:"Probity / Civil Service",
    q:"What do you understand by 'probity' in public life? What are the difficulties in practicing it? How can these difficulties be overcome?" },
  { id:"Q127", y:2014, sec:"A", m:"10 marks", th:"T8",
    f:"Accountability / Probity",
    q:"What does 'accountability' mean in the context of public service? What are the different measures that can be adopted to ensure individual and collective accountability?" },
  { id:"Q128", y:2024, sec:"B", m:"25 marks", th:"T8",
    f:"Administrative Ethics / Resource Management / Public Service",
    q:"A District Collector is faced with a severe water crisis in his district. A prolonged drought has drastically reduced water availability, forcing strict conservation measures. The local farming community, whose livelihoods depend on irrigation, is in conflict with an industrial zone that has a legal right to use a significant portion of the water supply. [Sub-questions: (a) What options are available to the District Collector to resolve this crisis? (b) What measures can be taken to address the interests of all stakeholders? (c) What are the administrative and ethical dilemmas involved in this scenario?]" },
  { id:"Q129", y:2020, sec:"B", m:"20 marks", th:"T8",
    f:"Public Finance Ethics / Administrative Dilemma",
    q:"Rajesh Kumar is a senior officer in Ministry of Finance handling national budget. Housing Scheme allocation of Rs. 8300 crores and a Special Economic Zone (for a natural gas processing plant) both need funds. Rs. 6000 crore re-appropriation from housing scheme to SEZ is proposed. [Sub-questions: (a) Ethical issues involved in re-appropriation of funds from a welfare project to developmental projects. (b) Given the need for proper utilization of public funds, discuss the options available to Rajesh Kumar. Is resigning a worthy option?]" },
  { id:"Q130", y:2019, sec:"B", m:"20 marks", th:"T8",
    f:"Civil Service Ethics / Legal Protection",
    q:"Honest civil servants who make bonafide mistakes during discharge of duties are being prosecuted, face imprisonment, resulting in loss of morale in civil services. [Sub-questions: (a) How does this trend affect the functioning of civil services? (b) What measures would you suggest to ensure that honest civil servants are not implicated for bonafide mistakes? Justify your answer.]" },
  { id:"Q131", y:2019, sec:"B", m:"20 marks", th:"T8",
    f:"Political-Bureaucratic Ethics / Good Governance",
    q:"The relationship between political executives and permanent executives is deteriorating. Political leaders intervene in administrative matters and lack respect for upright civil servants. Rising materialism has affected ethical values of both. [Sub-questions: Discuss the consequences of this 'politicization of bureaucracy'.]" },
  { id:"Q132", y:2019, sec:"B", m:"20 marks", th:"T8",
    f:"Civil Service Ethics / Institutional Reform",
    q:"Suggest institutional measures to address the following three dimensions of an effective civil service ethics framework: (a) Anticipating threats to ethical standards. (b) Strengthening ethical competence. (c) Developing administrative processes that promote ethical values and integrity." },
  { id:"Q133", y:2017, sec:"B", m:"20 marks", th:"T8",
    f:"RTI / Transparency / Administrative Ethics",
    q:"You are a Public Information Officer (PIO) in a government department. You are aware that the RTI Act 2005 envisages transparency and accountability in administration. Some RTI applications appear filed for ulterior motives while some activists extort officials. [Sub-questions: Suggest measures to separate genuine applications from nongenuine ones, with merits and demerits of your suggestions.]" },
  { id:"Q134", y:2016, sec:"B", m:"12 marks", th:"T8",
    f:"NGO Ethics / Bureaucratic Reform",
    q:"Saraswati, a successful IT professional from the USA, returns to India with patriotic intentions and forms an NGO with friends to build a school for a poor rural community. She encounters excessive bureaucratic delays, callous officials, and bribery demands. Suggest measures to ensure government control over NGOs while not thwarting well-meaning, honest NGO efforts." },
  { id:"Q135", y:2023, sec:"A", m:"10 marks", th:"T9",
    f:"Probity / Corruption / Values",
    q:"'Corruption is the manifestation of the failure of core values in the society.' In your opinion, what measures can be adopted to uplift the core values in the society?" },
  { id:"Q136", y:2022, sec:"A", m:"10 marks", th:"T9",
    f:"Whistleblowing / Probity",
    q:"Whistle-blower, who reports corruption and illegal activities, wrongdoing and misconduct to the concerned authorities, runs the risk of being exposed to grave danger, physical harm and victimization by the vested interests, accused persons and his team. What policy measures would you suggest to strengthen the protection mechanism to safeguard the whistle-blower?" },
  { id:"Q137", y:2021, sec:"A", m:"10 marks", th:"T9",
    f:"Probity / Anti-Corruption",
    q:"Elaborate on the policy of 'Zero Tolerance for Corruption' — Is it an ideal model for public administration? [Or: Is independent evaluation / social audit mechanism indispensable for good governance? Justify.]" },
  { id:"Q138", y:2019, sec:"A", m:"10 marks", th:"T9",
    f:"Civil Service Values / Corruption",
    q:"Non-performance of duty by a public servant is a form of corruption. Do you agree with this view? Justify your answer." },
  { id:"Q139", y:2018, sec:"A", m:"10 marks", th:"T9",
    f:"Conflict of Interest / Ethics",
    q:"What is meant by conflict of interest? Illustrate with examples, the difference between actual and potential conflicts of interest." },
  { id:"Q140", y:2017, sec:"A", m:"10 marks", th:"T9",
    f:"Conflict of Interest / Civil Service Ethics",
    q:"Conflict of interest in the public sector arises when (a) official duties, (b) public interest, and (c) personal interest are taking priority one above the other. How can this conflict in administration be resolved? Describe with an example." },
  { id:"Q141", y:2015, sec:"A", m:"10 marks", th:"T9",
    f:"Probity / Anti-Corruption / Governance",
    q:"Despite the codes of conduct, vigilance cells, RTI, media, and the legal mechanisms, corruption is still rampant. (a) Evaluate the effectiveness of these measures. (b) Suggest more effective strategies to tackle corruption." },
  { id:"Q142", y:2015, sec:"A", m:"10 marks", th:"T9",
    f:"Conflict of Interest",
    q:"'Conflict of interest' manifests itself in the public servant's decision-making process. Explain with examples. How would you resolve such situations if you are to confront them?" },
  { id:"Q143", y:2014, sec:"A", m:"10 marks", th:"T9",
    f:"Corruption / Probity",
    q:"Poverty leads to corruption; yet affluent people are also corrupt. What are the basic causes of corruption? Explain with examples." },
  { id:"Q144", y:2023, sec:"B", m:"20 marks", th:"T9",
    f:"Corruption / Whistleblowing / Civil Service Ethics",
    q:"Vinod is an IAS officer serving in a state government. He comes across evidence of large-scale corruption involving a high-ranking politician. He prepares a detailed report to send to the Anti-Corruption Bureau. But his colleague warns him that the politician has connections with the State Chief Minister and the matter could be used against him. [Sub-questions: (a) Evaluate each of the options available to Vinod. (b) Do you think 'politicization of bureaucracy' is a significant factor in such situations?]" },
  { id:"Q145", y:2018, sec:"B", m:"20 marks", th:"T9",
    f:"Conflict of Interest / Corruption / Political Pressure",
    q:"As a senior officer in a ministry with access to mega road project details, a Minister insists on project realignment toward his farmland and offers your wife property purchase assistance. This realignment requires extensive agricultural land acquisition, farmer displacement, and deforestation. Critically examine conflicts of interest and your responsibilities as a civil servant." },
  { id:"Q146", y:2018, sec:"B", m:"20 marks", th:"T9",
    f:"Whistleblowing / Civil Disobedience / Privacy Ethics",
    q:"Edward Snowden leaked confidential government surveillance documents to the public, violating the Espionage Act, claiming a moral obligation to inform citizens about government actions. Were Snowden's actions ethically justified despite being legally prohibited? Debate the ethical dimensions." },
  { id:"Q147", y:2015, sec:"B", m:"25 marks", th:"T9",
    f:"Administrative Ethics / Heritage / Corruption",
    q:"You head district administration. A senior officer schedules a site visit for a proposed school at Rampur village. Files show panchayat land acquired at nominal cost with incomplete certifications. Your visit reveals the plots its on the Thakurgarh fort with ramparts present. School location is inconvenient for children, heritage site concerns are unaddressed, and the previous Sarpanch was a relative of your predecessor. (a) List likely vested interests of concerned parties. (b) Discuss merits / demerits of four options: (i) await superior's decision, (ii) seek written / phone advice, (iii) consult predecessor / colleagues, (iv) find alternate plot and send comprehensive report. Suggest alternative options." },
  { id:"Q148", y:2014, sec:"B", m:"20 marks", th:"T9",
    f:"Business Ethics / Corruption",
    q:"You are CEO of a company manufacturing better quality and lower cost equipment than competitors. A government officer demands a bribe to clear your project. Evaluate arguments for and against bribe payment; suggest a third way." },
  { id:"Q149", y:2014, sec:"B", m:"20 marks", th:"T9",
    f:"Whistleblowing / Administrative Ethics / Integrity",
    q:"Rameshwar discovers departmental malpractices: fund misappropriation, facility misuse, recruitment irregularities with exam cheating. His seniors advise silence. Indicate options available and an evaluation framework for the best course of action." },
  { id:"Q150", y:2014, sec:"B", m:"20 marks", th:"T9",
    f:"Conflict of Interest / Academic Ethics / Integrity",
    q:"A technical institute's head chairs an upcoming professor selection interview. Days before, the Personal Secretary of a senior government functionary calls seeking intervention for a relative's selection, assuring pending funding proposals will be cleared in exchange. (a) What are the options available? (b) Evaluate each and state the option you would adopt, giving reasons." },
  { id:"Q151", y:2014, sec:"B", m:"20 marks", th:"T9",
    f:"Insider Information / Conflict of Interest / Probity",
    q:"As a Finance Ministry senior officer with access to confidential housing policy decisions, a builder who has done quality government work and is close to your superior requests early disclosure of policy details for profit. (a) What are the options available? (b) Evaluate each and state the option you would adopt." },
  { id:"Q152", y:2013, sec:"B", m:"20 marks", th:"T9",
    f:"RTI / Whistleblowing / Administrative Ethics",
    q:"A Public Information Officer has received an application under RTI Act. Having gathered the information, the PIO discovers that the information pertains to some of the decisions taken by him, which were found to be not altogether right. There were other employees also who were party to these decisions. Disclosure of the information is likely to lead to disciplinary action with possibility of punishment against him as well as some of his colleagues. Non-disclosure or part disclosure or camouflaged disclosure of information will result into lesser punishment or no punishment. The PIO is otherwise an honest and conscientious person but this particular decision, on which the RTI application has been filed, turned out to be wrong. He comes to you for advice. Evaluate the merits and demerits of the suggested options, and indicate what you would advise, giving proper reasons." },
  { id:"Q153", y:2013, sec:"B", m:"20 marks", th:"T9",
    f:"Conflict of Interest / Academic Ethics",
    q:"You are heading a leading technical institute of the country. The institute is planning to convene an interview panel shortly under your chairmanship for selection of the post of professors. A few days before the interview, you get a call from the Personal Secretary (PS) of a senior government functionary seeking your intervention in favour of the selection of a close relative of the functionary for this post. The PS also informs you that he is aware of the long pending and urgent proposals of your institute for grant of funds for modernization, which are awaiting the functionary's approval. He assures you that he would get these proposals cleared. (a) What are the options available to you? (b) Evaluate each of these options and choose the option which you would adopt, giving reasons." },
  { id:"Q154", y:2013, sec:"B", m:"20 marks", th:"T9",
    f:"Insider Information / Probity / Conflict of Interest",
    q:"As a senior officer in the Finance Ministry, you have access to some confidential and crucial information about policy decisions that the Government is about to announce. These decisions are likely to have far-reaching impact on the housing and construction industry. If the builders have access to this information beforehand, they can make huge profits. One of the builders has done a lot of quality work for the Government and is known to be close to your immediate superior, who asks you to disclose this information to the said builder. (a) What are the options available to you? (b) Evaluate each of these options and choose the option which you would adopt, giving reasons." },
  { id:"Q155", y:2023, sec:"A", m:"10 marks", th:"T10",
    f:"Corporate Ethics / Integrity",
    q:"What do you understand by 'moral integrity' and 'professional efficiency' in the context of corporate governance in India? Illustrate with suitable examples." },
  { id:"Q156", y:2023, sec:"A", m:"10 marks", th:"T10",
    f:"Workplace Ethics",
    q:"In the context of work environment, differentiate between 'coercion' and 'undue influence' with suitable examples." },
  { id:"Q157", y:2023, sec:"B", m:"20 marks", th:"T10",
    f:"Banking Ethics / Integrity / Loyalty",
    q:"Suresh's colleague Sanjay is unable to pay the medical bills for his father's surgery. Sanjay, after much deliberation, transfers money from a dormant account of a customer to his own account. Suresh comes to know of this. [Sub-questions: (a) What are the ethical issues involved? (b) Evaluate the behaviour of Sanjay. (c) As Suresh, what would be your response?]" },
  { id:"Q158", y:2023, sec:"B", m:"20 marks", th:"T10",
    f:"Work-Life Balance / Gender / Civil Service Values",
    q:"Rashika is a Joint Secretary in a Central Ministry. She is known for her integrity and efficiency. As a woman, she is also sensitive to gender issues. She is a single mother and her daughter is preparing for a competitive examination. Due to excessive workload, she is not able to spend time with her daughter. Her colleagues, who are less than efficient, manage to complete their routine work well within time and spend time with their families. [Sub-questions: (a) Discuss the ethical issues involved in this case. (b) Mention the relevant laws / rules which are made for the welfare of women who are working in government / formal sectors. (c) What suggestions would you give to mitigate the issues mentioned in the case?]" },
  { id:"Q159", y:2023, sec:"B", m:"20 marks", th:"T10",
    f:"Workplace Ethics / Harassment / Gender",
    q:"Seema is a newly recruited architect in the Public Works Department. She has innovative ideas and is hardworking. Her senior, who is jealous of her talent, systematically belittles her, gives her unimportant work, and takes credit for her ideas. This affects her mental health and she considers resigning. [Sub-questions: (a) Identify the ethical issues in this case. (b) What options are available to retain Seema and ensure good work? (c) What would be your response if you were Seema?]" },
  { id:"Q160", y:2022, sec:"B", m:"20 marks", th:"T10",
    f:"Corporate Ethics / Business Ethics",
    q:"Prabhat was working as Vice President (Marketing) at Sterling Electric Ltd., a reputed multinational company. But presently the company was passing through the difficult times asthe sales were continuously showing downward trend in the last two quarters. The company's products were also facing stiff competition from cheaper Chinese imports. One fine morning, Prabhat was called by the CEO of the company, who said that if the company does not perform better, then the company may have to wind up its operations in India. The CEO handed over a list of retailers, dealers, and stockists who had defaulted in clearing their dues worth hundreds of crores of rupees. [Sub-questions: (a) Discuss the ethical issues involved in the case. (b) Critically examine the options available to Prabhat in the above situation. (c) Which of the above would be the most appropriate for Prabhat and why?]" },
  { id:"Q161", y:2021, sec:"B", m:"20 marks", th:"T10",
    f:"Workplace Ethics / Harassment / Mental Health",
    q:"Officer Pawan is transferred to a new department. His senior officer systematically belittles him, publicly humiliates him, and assigns no meaningful work without legitimate justification. This damages his confidence, family relationships, and mental health. [Sub-questions: (a) Options available to Pawan for coping. (b) Approach for restoring office and home peace. (c) Suggestions for both boss and subordinate. (d) Training recommendations for government officers.]" },
  { id:"Q162", y:2019, sec:"B", m:"20 marks", th:"T10",
    f:"Workplace Ethics / Sexual Harassment",
    q:"An apparel manufacturing company with many women employees hires a marketing executive who boosts sales. Unconfirmed reports emerge of sexual harassment. A formal complaint is filed and FIR registered. The company offers her substantial money to withdraw both the complaint and FIR. [Sub-questions: (a) Identify the ethical issues involved in the case. (b) What options are available to the woman employee?]" },
  { id:"Q163", y:2017, sec:"B", m:"20 marks", th:"T10",
    f:"Labour Ethics / Corporate Ethics",
    q:"You are the head of the Human Resources department of an organization. One day one of the workers dies on duty while intoxicated. The company denies compensation; workers strike. [Sub-questions: (a) What recommendation would you provide to the management? (b) Discuss the merits and demerits of each recommendation.]" },
  { id:"Q164", y:2017, sec:"B", m:"20 marks", th:"T10",
    f:"Business Ethics / Ethical Dilemma / Witness Duty",
    q:"You are the manager of a spare parts company and have to negotiate a deal with the manager of a large manufacturing company. You witness the manufacturing company manager hit a motorcyclist while driving fast. As sole eyewitness, disclosing the truth jeopardizes an important business deal. [Sub-questions: (a) What are the dilemmas you face? (b) What will be your response?]" },
  { id:"Q165", y:2016, sec:"B", m:"12 marks", th:"T10",
    f:"Workplace Ethics / Domestic Violence / Moral Courage",
    q:"You are a junior government employee. Your respected boss invites you to his home for work but you witness signs of domestic violence against his wife. Office inquiries later confirm he beats his wife. She is uneducated and vulnerable. Analyze each option: (a) Ignore it as a personal matter. (b) Report to appropriate authorities. (c) Your own innovative approach." },
  { id:"Q166", y:2015, sec:"B", m:"20 marks", th:"T10",
    f:"Corporate Ethics / Political Pressure / Leadership",
    q:"A private company known for efficiency, transparency, and employee welfare has about 700 employees and no union. Suddenly, 40 political party members forcefully entered demanding jobs while threatening staff and using abusive language. As CEO: (a) How would you diffuse this volatile situation immediately? (b) What long-term solutions address the underlying issue? (c) Analyze positive and negative consequences of suggested actions." },
  { id:"Q167", y:2014, sec:"B", m:"20 marks", th:"T10",
    f:"Civil Service Ethics / Sexual Harassment / Integrity",
    q:"An honest officer transferred to an inefficient department tries to enforce discipline but troublemakers file a false sexual harassment complaint against him. Three options available: (a) Compromise with environment, (b) Confront the situation, (c) Request transfer. Evaluate each with merits / demerits and suggest additional options." },
  { id:"Q168", y:2013, sec:"B", m:"20 marks", th:"T10",
    f:"Sexual Harassment / Corporate Ethics / Leadership",
    q:"You are the Executive Director of an upcoming Infotech Company which is making a name for itself in the market. Mr. A, who is a star performer, is heading the marketing team. In a short period of one year, he has helped in doubling the revenues as well as creating a high brand equity for the Company so much so that you are thinking of promoting him. However, you have been receiving information from many corners about his attitude towards the female colleagues, particularly his habit of making loose comments on women. In addition, he regularly sends indecent SMSs to all the team members including his female colleagues. One day, late in the evening, Mrs. X, who is one of Mr. A's team members, comes to you visibly disturbed. She complains against the continued misconduct of Mr. A, who has been making undesirable advances towards her and has even tried to touch her inappropriately in his cabin. She tenders her resignation and leaves your office. (a) What are the options available to you? (b) Evaluate each of these options and choose the option you would adopt, giving reasons." },
  { id:"Q169", y:2024, sec:"A", m:"12.5 marks", th:"T11",
    f:"International Ethics / War and Peace",
    q:"The ever-increasing arms trade is keeping the wars alive. In this context, what ethical considerations should the powerful nations keep in mind in today's international arena to stop the continuation of ongoing conflicts?" },
  { id:"Q170", y:2023, sec:"A", m:"10 marks", th:"T11",
    f:"International Ethics / Aid",
    q:"'International aid' is an accepted form of helping 'resource-challenged' nations. Comment on 'ethics in contemporary international aid'. Support your answer with suitable examples." },
  { id:"Q171", y:2022, sec:"A", m:"10 marks", th:"T11",
    f:"International Ethics / War",
    q:"Russia and Ukraine war has been going on for the last seven months. Different countries have taken independent stands and actions keeping in view their own national interests. What are those ethical issues that are crucial to be considered while launching the war and its continuation so far? Illustrate with justification the ethical issues involved in the given state of affairs." },
  { id:"Q172", y:2021, sec:"A", m:"10 marks", th:"T11",
    f:"International Ethics / Human Rights / Democracy",
    q:"Should the democratic values of an elected government have primacy over the human rights of non-citizens? Examine with suitable illustrations." },
  { id:"Q173", y:2017, sec:"A", m:"10 marks", th:"T11",
    f:"International Ethics",
    q:"'Strength, peace and security are considered to be the pillars of international relations.' Elucidate." },
  { id:"Q174", y:2015, sec:"A", m:"10 marks", th:"T11",
    f:"International Ethics",
    q:"International bilateral relations are increasingly governed by national interest without regard for the other nation's wellbeing, resulting in conflicts and tensions. How can ethical considerations help resolve such tensions? Discuss with examples." },
  { id:"Q175", y:2020, sec:"B", m:"20 marks", th:"T11",
    f:"Defence Ethics / Arms Export / International Ethics",
    q:"Bharat Missiles Ltd (BML) has developed Anti-Tank Guided Missiles (ATGM). The government is considering exporting these to other nations. As Chairman of BML: [Sub-questions: (a) What are your views on the Defence Minister's export announcement? (b) What are the ethical issues involved in arms trade for a responsible nation like India? (c) List five ethical factors that would influence the decision to sell arms to foreign governments.]" },
  { id:"Q176", y:2024, sec:"A", m:"12.5 marks", th:"T12",
    f:"Ethics and Technology / AI Ethics",
    q:"Application of Artificial Intelligence as a dependable source of input for administrative rational decision-making is a debatable issue. Critically examine the statement from the ethical point of view." },
  { id:"Q177", y:2022, sec:"A", m:"10 marks", th:"T12",
    f:"Good Governance / e-Governance",
    q:"What do you understand by the term 'good governance'? How far recent initiatives in terms of e-Governance steps taken by the State have helped the beneficiaries? Discuss with suitable examples." },
  { id:"Q178", y:2022, sec:"A", m:"10 marks", th:"T12",
    f:"Digital Ethics / Social Justice",
    q:"Online methodology is being used for day-to-day meetings, institutional approvals in the administration and for teaching and learning in the education sector to the extent telemedicine in the health sector is getting popular with the approval of the competent authority. Describe and discuss the ethical issues involved in the use of the online method, particularly to the vulnerable section of society." },
  { id:"Q179", y:2021, sec:"A", m:"10 marks", th:"T12",
    f:"Digital Ethics / Technology",
    q:"Impact of digital technology as a reliable source of input for rational decision making is a debatable issue. Critically evaluate with a suitable example." },
  { id:"Q180", y:2020, sec:"A", m:"10 marks", th:"T12",
    f:"Digital Ethics / Media Ethics",
    q:"Internet is not only regarded as a tool for the provision of information and communication but also a powerful tool for constructive as well as destructive purposes. Discuss with suitable examples the threats of internet in expanding alternate worldviews that sometimes challenge mainstream beliefs." },
  { id:"Q181", y:2024, sec:"B", m:"25 marks", th:"T12",
    f:"Corporate Ethics / Environmental Ethics / AI Ethics",
    q:"ABC Incorporated is the second largest tech company in the world. The company's greenhouse gas emissions have surged by 48% since 2019, primarily due to energy-intensive data centres supporting AI initiatives, putting its 2030 net-zero commitment in jeopardy. The company is torn between its ambitious AI-driven growth strategy and its environmental sustainability commitments. [Sub-questions: (a) As the CEO of ABC Incorporated, what would be your immediate response to address this environmental challenge without compromising on AI innovation? (b) What are the ethical considerations involved in balancing technological innovation, profitability, and environmental responsibility? (c) What justification would you offer for imposing penalties on companies that fail to meet their sustainability commitments? (d) What measures would you suggest to maintain the equilibrium between technological advancement and environmental sustainability?]" },
  { id:"Q182", y:2024, sec:"B", m:"25 marks", th:"T12",
    f:"Conflict of Interest / Medical Ethics",
    q:"Sneha is a senior hospital manager overseeing procurement of medical equipment. When processing a tender for surgical equipment, she discovers that one of the bidders is a company owned by her brother, who is in dire financial straits. [Sub-questions: (a) What is the appropriate action Sneha should take in this situation? (b) How would you justify this course of action to your brother who is in need? (c) In what ways could Sneha's decision be influenced by the principles of medical ethics?]" },
  { id:"Q183", y:2024, sec:"B", m:"25 marks", th:"T12",
    f:"Bioethics / Research Ethics / Medical Ethics",
    q:"Dr. Srinivasan is a lead scientist in a pharmaceutical company working on a drug trial for a potentially lifesaving medication. As the project nears completion, he faces pressure from management to expedite the trials by manipulating data and cutting corners on informed consent procedures. [Sub-questions: (a) How should Dr. Srinivasan approach this ethical dilemma in his decision-making? (b) Critically examine the ethical issues involved in this case. (c) How does the ethical framework around data integrity and drug trials protect public health?]" },
  { id:"Q184", y:2023, sec:"B", m:"20 marks", th:"T12",
    f:"Bioethics / Medical Ethics / Disaster Management",
    q:"During a landslide disaster relief operation, you are a doctor and the only blood of the type O-negative is available with a pregnant woman. She refuses to give blood for religious reasons. A severely injured youth will die without the transfusion. [Sub-questions: (a) What are the ethical issues involved? (b) Evaluate the options available to the doctor.]" },
  { id:"Q185", y:2023, sec:"B", m:"20 marks", th:"T12",
    f:"Media Ethics / Cyberbullying / Social Media",
    q:"A video, defamatory in nature about a student's parent (who is a government officer), goes viral on social media. The student, deeply troubled, posts a counter-video which also becomes viral. [Sub-questions: (a) Discuss the ethical issues involved in the use of social media in this case. (b) Examine the pros and cons of the student's response.]" },
  { id:"Q186", y:2021, sec:"B", m:"20 marks", th:"T12",
    f:"Engineering Ethics / Political Pressure / Safety",
    q:"You are a project manager heading construction of an elevated corridor. Inspecting teams find minor cracks in piers. The Chief Engineer orders you to ignore the defects to meet the Chief Minister's pre-election inauguration deadline. The contractor is the minister's relative and your promotion depends on compliance. [Sub-questions: (a) Options available as project manager. (b) Ethical dilemmas and responses. (c) Professional challenges and responses. (d) Consequences of overlooking inspection observations.]" },
  { id:"Q187", y:2021, sec:"B", m:"20 marks", th:"T12",
    f:"Medical Ethics / Disaster Management / Public Administration",
    q:"You are a public hospital administrator during peak COVID-19 cases (May 2020). Infrastructure is severely limited with shortage of beds, oxygen, and staff. [Sub-questions: (a) What criteria and justification would you apply for deploying clinical / non-clinical staff knowing infection risk with limited resources? (b) Would your decision differ if you were managing a private hospital?]" },
  { id:"Q188", y:2021, sec:"B", m:"20 marks", th:"T12",
    f:"Corporate Ethics / Food Safety / Consumer Ethics",
    q:"A company exported approved products but sold domestically the rejected export batches, violating health standards. Discovery damaged reputation and profits significantly. [Sub-questions: (a) Actions the competent authority should take. (b) Course of action for company crisis recovery. (c) Ethical dilemmas involved.]" },
  { id:"Q189", y:2020, sec:"B", m:"20 marks", th:"T12",
    f:"Construction Ethics / Political Pressure / Public Safety",
    q:"You are a municipal commissioner. During surprise inspection of mall construction, roof collapses due to material quality issues. Unauthorized basement construction and zoning violations are found. Builder is politically connected and seniors pressure you to go easy. [Sub-questions: (a) Discuss the ethical issues involved in the case. (b) What are the options available to you in this situation? (c) Explain your selected course of action.]" },
  { id:"Q190", y:2018, sec:"B", m:"20 marks", th:"T12",
    f:"Medical Ethics / Tax Compliance / Public Interest",
    q:"Dr. X, through a charitable trust, plans a super-specialty hospital for a neglected region serving all sections of society. A tax investigation reveals substantial financial irregularities requiring immediate payment and technical defaults. Two options: (a) Take a broader view, ensure substantial compliance while ignoring technical defaults. (b) Strictly pursue all matters regardless. Which approach would you take and why?" },
  { id:"Q191", y:2017, sec:"B", m:"20 marks", th:"T12",
    f:"Construction Ethics / Regulatory Failure",
    q:"A building permitted for three floors was illegally extended to six floors by a builder and collapses, resulting in multiple deaths including migrant labourers and children. [Sub-questions: (a) Give reasons why such incidents keep taking place across the country. (b) Suggest measures to prevent their occurrence.]" },
  { id:"Q192", y:2015, sec:"B", m:"20 marks", th:"T12",
    f:"Bioethics / Corporate Ethics / Social Justice",
    q:"A pharmaceutical R&D scientist discovers the company's veterinary drug could cure an incurable liver disease in tribal areas. Human variant requires Rs. 50 crore investment with minimal cost recovery in impoverished regions. If you were CEO: (a) Identify possible actions. (b) Evaluate pros and cons of each action." },
  { id:"Q193", y:2013, sec:"B", m:"20 marks", th:"T12",
    f:"Engineering Ethics / Safety / Administrative Courage",
    q:"You are working as an Executive Engineer in the construction cell of a Municipal Corporation and are presently in-charge of the construction of a flyover. There are two Junior Engineers under you who have the responsibility of day-to-day inspection of the site and are reporting to you, while you are finally reporting to the Chief Engineer who heads the cell. While the construction is heading towards completion, the Junior Engineers have been regularly reporting that all construction is taking place as per design specifications. However, in one of your surprise inspections, you have noticed some serious deviations and lacunae which, in your opinion, are likely to affect the safety of the flyover. Rectification of these lacunae at this stage would require a substantial amount of demolition and rework which will cause a tangible loss to the contractor and will also delay completion. There is a lot of public pressure on the Corporation to get this construction completed because of heavy traffic congestion in the area. When you brought this matter to the notice of the Chief Engineer, he advised you that in his opinion it is not a very serious lapse and may be ignored. He advised for further expediting the project for completion in time. However, you are convinced that this was a serious matter which might affect public safety and should not be left unaddressed. What will you do in such a situation? Evaluate the merits and demerits of each of the given options and finally suggest what course of action you would like to take, giving reasons." },
  { id:"Q194", y:2024, sec:"A", m:"12.5 marks", th:"T13",
    f:"Environmental Ethics",
    q:"Human greed has resulted in global warming, causing unprecedented changes and impending catastrophe. How can we end this threat to life as we know it and bring about a balance between society and environment?" },
  { id:"Q195", y:2022, sec:"A", m:"10 marks", th:"T13",
    f:"Corporate Ethics / CSR / Environment",
    q:"In the contemporary world, the corporate sector's contribution to generating wealth and employment is increasing. In doing so, they are bringing in an unprecedented onslaught on the climate, environmental sustainability and living conditions of human beings. Do you find that Corporate Social Responsibility (CSR) is efficient and sufficient enough to fulfil the social roles and responsibilities needed in the corporate world? Critically examine." },
  { id:"Q196", y:2018, sec:"A", m:"10 marks", th:"T13",
    f:"Development Ethics / Environmental Ethics",
    q:"Suppose a rational and sensitive person is constructing a dam in a forested and ethnically inhabited mountain valley. What are the unforeseen consequences that may result from the policy of constructing dam? Suggest a rational policy considering the unforeseen contingencies." },
  { id:"Q197", y:2017, sec:"A", m:"10 marks", th:"T13",
    f:"Corporate Ethics / CSR",
    q:"Corporate social responsibility makes companies more profitable and sustainable. Analyse." },
  { id:"Q198", y:2017, sec:"A", m:"10 marks", th:"T13",
    f:"Social Justice / Development Ethics",
    q:"'Increased national wealth did not result in equitable distribution of its benefits. It has created only some enclaves of modernity and prosperity for a small minority at the cost of the majority.' Justify." },
  { id:"Q199", y:2015, sec:"A", m:"10 marks", th:"T13",
    f:"Environmental Ethics",
    q:"What is meant by 'environmental ethics'? Why is it important to study? Discuss any one environmental issue from the viewpoint of environmental ethics." },
  { id:"Q200", y:2022, sec:"B", m:"20 marks", th:"T13",
    f:"Environmental Ethics / Administrative Dilemma / Corruption",
    q:"You are appointed as an officer heading the section in Environment Pollution Control Board to ensure compliance and its follow-up. In that region, there were large number of small and medium industries which had been granted clearance. You learnt that these industries provide employment to many migrant workers. Most of the industrial units have got environmental clearance certificate in their possession but many of these have been obtained illegally by bribing the officials. [Sub-questions: (a) What are the options available to you under the given situation? (b) Critically examine the options listed by you. (c) What type of mechanism would you suggest to ensure environmental compliance? (d) What are the ethical dilemmas you faced in exercising your option?]" },
  { id:"Q201", y:2022, sec:"B", m:"20 marks", th:"T13",
    f:"Corporate Ethics / Labour Ethics / Environmental Ethics",
    q:"You have done MBA from a reputed institution three years back but could not get campus placement due to COVID-19 generated recession. However, after a lot of persuasion and series of competitive tests including written and interview, you managed to get a job in a leading shoe company. As part of your job, you are to go with a team for inspection of some shoe manufacturing companies. During inspection, you found that one of the factories was violating various labour laws and also causing environmental degradation. [Sub-questions: (a) Under the given conditions, what are the options available to you as a member of the Inspecting Team? (b) Critically evaluate each of the options listed by you. (c) What option would you adopt and why? (d) What are the ethical dilemmas being faced by you? (e) What can be the consequences of overlooking the observations raised by the inspecting Team?]" },
  { id:"Q202", y:2022, sec:"B", m:"20 marks", th:"T13",
    f:"Police Ethics / Environmental Protection / Political Corruption",
    q:"The Supreme Court has banned mining in the Aravalli Hills to stop degradation of the forest cover and to maintain ecological balance. However, the stone mining was still prevalent in the border district of the affected State with connivance of certain corrupt forest officials and politicians. Ashok, a young IPS officer, was posted as the Superintendent of Police in that district. [Sub-questions: (a) What are the options available with Ashok to cope up with the situation? (b) Critically evaluate / examine each of the options identified by Ashok. (c) What are the ethical dilemmas being faced by Ashok? (d) Which of the options, do you think, would be the most appropriate for Ashok to adopt and why? (e) In the above scenario, what type of training would you suggest for police officers posted to such districts where stone mining illegal activities are rampant?]" },
  { id:"Q203", y:2020, sec:"B", m:"20 marks", th:"T13",
    f:"Corporate Social Responsibility / Development Ethics",
    q:"Anil establishes Amria Plastic Works (APW) in poor village Noora. APW provides employment, schools, hospitals (CSR). However a fire incident raises questions about safety and governance. [Sub-questions: (a) Critically analyse the story of APW and state the ethical issues involved. (b) Do you consider APW as a role model for development of backward areas? Give reasons.]" },
  { id:"Q204", y:2018, sec:"B", m:"20 marks", th:"T13",
    f:"Environmental Ethics / Industrial Ethics / Administrative Dilemma",
    q:"A large industrial chemical company, rejected by many states, establishes a unit near a city despite environmental concerns. Ten years later, pollution severely damages land, water, crops, and health. Public agitation forces closure, creating worker unemployment and ancillary industry collapse. As a senior officer, how would you address this issue?" },
  { id:"Q205", y:2016, sec:"B", m:"12 marks", th:"T13",
    f:"Corporate Ethics / Development Ethics / CSR",
    q:"ABC Ltd., a large transnational company, plans an energy-efficient plant in Vikaspuri, an underdeveloped area. The project aligns with government policy but threatens the region's tranquility by increasing living costs, attracting migration, and disrupting social and economic order. Despite CSR initiatives, residents protest. (a) Identify the issues involved. (b) What can be suggested to satisfy the company's goal and address residents' concerns?" },
  { id:"Q206", y:2016, sec:"B", m:"12 marks", th:"T13",
    f:"Development Ethics / Displacement / Tribal Rights",
    q:"Land for mining, dams, and large-scale projects is acquired mostly from Adivasis and rural communities. Displaced persons lack marketable skills and become low-paid migrant labourers, while development goes to industries and costs are passed to poor people. Draft a better compensation-cum-rehabilitation policy addressing this unjust distribution of costs and benefits." },
  { id:"Q207", y:2016, sec:"B", m:"12 marks", th:"T13",
    f:"Whistleblowing / Environmental Ethics / Moral Courage",
    q:"A fresh engineering graduate discovers her chemical company secretly discharges toxic waste into a nearby river, causing health problems in downstream villages. Colleagues advise silence, warning that whistleblowers are dismissed. She is her family's sole breadwinner. (a) What arguments show that keeping quiet is not morally right? (b) What course of action would you advise and why?" },
  { id:"Q208", y:2014, sec:"B", m:"20 marks", th:"T13",
    f:"Environmental Ethics / Development Ethics",
    q:"Sustainable development and environmental protection have come into conflict in the context of economic development. Discuss feasible strategies for sustainable development that can eliminate this conflict." },
  { id:"Q209", y:2024, sec:"A", m:"12.5 marks", th:"T14",
    f:"Civil Service Values / Gender",
    q:"Female public servants face gender-specific challenges while performing their duties. Suggest measures that can enable them to overcome these challenges and enhance their operational effectiveness while maintaining high standards of probity." },
  { id:"Q210", y:2020, sec:"A", m:"10 marks", th:"T14",
    f:"Social Ethics / Gender",
    q:"What are the main factors responsible for gender inequality in India? Discuss the contribution of Savitribai Phule in this regard." },
  { id:"Q211", y:2014, sec:"A", m:"10 marks", th:"T14",
    f:"Social Ethics / Gender",
    q:"Sexual violence against women is a global phenomenon and India is no exception. Despite legal provisions, it continues. Suggest innovative measures to effectively tackle this problem." },
  { id:"Q212", y:2022, sec:"B", m:"20 marks", th:"T14",
    f:"Labour Rights / Administrative Ethics",
    q:"Rakesh was working as Joint Commissioner in Transport Department of a city. As a part of his job profile, among others, he was entrusted with the task of overseeing the control and functioning of City Transport Department. A case of strike by the drivers' union was reported. [Sub-questions: (a) What are the options available to Rakesh to meet the above situation? (b) Critically examine each of the options identified by Rakesh. (c) What are the ethical dilemmas being faced by Rakesh? (d) What course of action would Rakesh adopt to diffuse the above situation?]" },
  { id:"Q213", y:2020, sec:"B", m:"20 marks", th:"T14",
    f:"Child Labour / Tribal Rights / Social Ethics",
    q:"In Rampura district, tribal girls below 14 years work in Bt cotton farms and suffer health deterioration. NGOs supposed to help have been compromised. As District Collector: [Sub-questions: (a) Identify the ethical issues involved. (b) What specific steps will you initiate to ameliorate the conditions of minor girls and improve the overall economic scenario of the district?]" },
  { id:"Q214", y:2020, sec:"B", m:"20 marks", th:"T14",
    f:"Social Ethics / Labour Rights / Governance",
    q:"Migrant workers have always remained at the socio-economic margins of our society, silently serving as the instrumental labour force of urban economics. The pandemic has brought them into national focus. [Sub-questions: (a) What ethical issues arose in the current migrant crisis? (b) What do you understand by an ethical care-giving state? (c) What assistance can the civil society render to mitigate the sufferings of migrants in similar situations?]" },
  { id:"Q215", y:2018, sec:"B", m:"20 marks", th:"T14",
    f:"Administrative Ethics / Social Justice / Rule vs Compassion",
    q:"Rakesh is a district officer identifying eligible beneficiaries for a senior citizen health scheme. An elderly couple meets all four criteria except reserved community status. Surgery costs require one lakh rupees; financial aid would significantly improve their quality of life. How should Rakesh respond? Evaluate options with justifications." },
  { id:"Q216", y:2016, sec:"B", m:"12 marks", th:"T14",
    f:"Administrative Ethics / Social Justice / Rule vs Compassion",
    q:"An old, illiterate woman seeks benefits from a social service scheme for destitute women. Your inquiry confirms she genuinely needs support, but she lacks required documentation. Approving her violates rules; denying her is cruel and inhuman. (a) Can you think of a rational way to resolve this dilemma? (b) Give your reasons." },
  { id:"Q217", y:2015, sec:"B", m:"20 marks", th:"T14",
    f:"Social Ethics / Caste Discrimination / Governance",
    q:"You are a Panchayat Sarpanch. The government primary school provides midday meals. A new cook appointed from the Dalit community causes higher-caste parents to prevent their children from taking meals. School attendance drops sharply, threatening scheme discontinuation, staff reduction, and school closure. (a) Discuss feasible strategies to overcome conflict and create positive ambiance. (b) What responsibilities should different social segments and agencies assume?" },
  { id:"Q218", y:2015, sec:"B", m:"25 marks", th:"T14",
    f:"Gender Ethics / Child Rights / Social Reform",
    q:"A recently posted district development officer finds rural tension regarding girls' education. Elders believe educated girls cause problems and prefer early marriage. Younger generation advocates equal opportunity. Girls traveling to school were molested, sparking clashes. Elders decided to prohibit girls' schooling and socially boycott noncompliant families. (a) What steps ensure girls' safety without disrupting education? (b) How would you reshape patriarchal elder attitudes while maintaining intergenerational harmony?" },
  { id:"Q219", y:2014, sec:"B", m:"20 marks", th:"T14",
    f:"Social Ethics / Development / Migration",
    q:"Rural-to-urban migration is increasing drastically. Analyze the socio-economic, emotional, and attitudinal factors leading to: (a) Migration of educated youth, (b) Landless poor to urban slums, (c) Farmers selling land. Suggest feasible steps to control such migration." },
  { id:"Q220", y:2013, sec:"B", m:"25 marks", th:"T14",
    f:"Child Labour / Industrial Ethics / Law Enforcement",
    q:"Sivakasi in Tamil Nadu is known for its manufacturing clusters on firecrackers and matches. The local economy of the area is largely dependent on firecrackers industry. It has led to tangible economic development and improved standard of living in the area. So far as child labour norms for hazardous industries like firecrackers industry are concerned, International Labour Organization (ILO) has set the minimum age as 18 years. In India, however, this age is 14 years. The units in industrial clusters of firecrackers can be classified into registered and non-registered entities. One typical unit is household-based work. Though the law is clear on the use of child labour employment norms in registered and non-registered units, it does not include household-based works. Household-based work means children working under the supervision of their parents or relatives. To evade child labour norms, several units project themselves as household-based works but employ children from outside. Employing children saves the costs for these units leading to higher profits to the owners. On your visit to one of the units at Sivakasi, the owner takes you around the unit which has about 10-15 children below 14 years of age. The owner tells you that in his household-based unit, the children are all his relatives. You notice that several children smirk, when the owner tells you this. On deeper enquiry, you figure out that neither the owner nor the children are able to satisfactorily establish their relationship with each other. (a) Bring out and discuss the ethical issues involved in the above case. (b) What would be your reaction after your above visit?" },
];
