/* =====================================================================
   OPEN IT OUT WITH — the material behind each prompt
   ---------------------------------------------------------------------
   A prompt names an example; this file supplies the substance an essay
   needs to use it — the statute, the judgment, the number, the year.
   Keyed by the exact prompt string in answers.js, so a prompt with no
   entry here simply stays plain text. To add one, copy any block below.
     t : short title for the card
     p : one or more paragraphs
   ===================================================================== */
const OPENOUTS = {
  "Deterrence, no-first-use doctrine and the ethics of a threat never executed":{
    t:"No-first-use and the threat never carried out",
    p:["India's nuclear doctrine, adopted by the Cabinet Committee on Security in January 2003, rests on credible minimum deterrence and no first use. Nuclear weapons would be used only in retaliation against a nuclear attack on Indian territory or on Indian forces, and that retaliation would be massive, designed to inflict unacceptable damage. The doctrine also reserves a nuclear response to a major chemical or biological attack. The ethical difficulty is exact. Deterrence works only if the threat is believed, and it is believed only if the state is genuinely prepared to do what would be monstrous to do. The means are never used, but they must be sincerely intended. A threat nobody would carry out deters nobody."]},
  "Surgical strikes and calibrated response: force as signalling rather than as objective":{
    t:"Force as signal rather than as objective",
    p:["After the Uri attack of 18 September 2016, in which 19 soldiers were killed, Indian special forces struck launch pads across the Line of Control on 29 September. After the Pulwama bombing of 14 February 2019, which killed 40 CRPF personnel, the Air Force struck a camp at Balakot on 26 February. The Foreign Secretary described the second as a non-military pre-emptive action. The language was doing work. In neither case was the objective territory or attrition. The objective was a message that a threshold had moved. Force used as signalling is judged by what it communicates rather than by what it destroys, which makes proportionality harder to assess and escalation harder to control."]},
  "Economic sanctions — coercion without combat, and the civilian burden it transfers":{
    t:"Coercion without combat",
    p:["Sanctions promise pressure without bloodshed, but the burden often falls on people who had no say in the policy being punished. The United Nations imposed comprehensive sanctions on Iraq through Resolution 661 in August 1990. The humanitarian consequences were severe enough that the Security Council created the oil-for-food programme in December 1996 to relieve them, and that programme was itself criticised for delays, reparation deductions and politically motivated holds on contracts. The episode drove the later shift towards targeted sanctions aimed at named individuals, assets and specific sectors. The ethical issue is transfer. A measure presented as the alternative to war can impose war-like costs on civilians while leaving the leadership it targets comparatively untouched."]},
  "Encounter killings and preventive detention where a lawful end is pursued unlawfully":{
    t:"A lawful end pursued unlawfully",
    p:["In PUCL v State of Maharashtra (2014), the Supreme Court examined 99 encounters in which Mumbai police had killed 135 people between 1995 and 1997, and laid down sixteen guidelines for investigating deaths in police encounters. They carry the force of law under Article 141 and require independent investigation rather than acceptance of a claim of self-defence. Preventive detention runs on a parallel logic. Under the National Security Act 1980 a person may be held for three months before the case goes to an Advisory Board of three High Court judges, up to twelve months in all, with no right to a lawyer before that Board. Both are the state pursuing a lawful end by a route that bypasses proof."]},
  "Your counter-case: an outcome so grave that means genuinely become secondary":{
    t:"When the outcome may genuinely outweigh the route",
    p:["The strongest counter-case is one where the end is so large and so irreversible that ordinary objections look small. Smallpox is that case. In 1974 Bihar and Uttar Pradesh together accounted for roughly three-quarters of the world's smallpox cases. The campaign that ended it, culminating in Operation Smallpox Zero in 1975, worked by searching out every case and containing it. The historian Paul Greenough documented that the final stages involved intimidation and coercion, including people being tracked down and vaccinated against their will. India's last indigenous case was in May 1975 and the disease was declared eradicated worldwide in 1980. Carry the cost honestly as well. Greenough argues the resentment it created may have damaged trust in later vaccination campaigns."]},
  "Pendency in Indian courts and tribunals as decision-avoidance with a human cost":{
    t:"Pendency in Indian courts and tribunals",
    p:["Justice can be denied not only through a wrong decision but also through the failure to decide in time. As of December 2025, over 4.84 crore cases were pending in District and Subordinate Courts, more than 63 lakh in High Courts and around 90,900 in the Supreme Court. Many of these cases concern compensation, property, employment, pensions and other basic rights. A person may eventually receive a favourable judgment, but after waiting for years, the relief may lose much of its value. Thus, delay is not the absence of action; it can itself become a form of injustice."]},
  "Regulatory forbearance in banking — the years before NPAs were recognised":{
    t:"Regulatory forbearance in banking",
    p:["Delaying recognition of a problem can sometimes make the eventual solution much harder. During India's banking stress, regulatory forbearance allowed banks to postpone recognising some restructured loans as NPAs. The Economic Survey noted that this encouraged banks to restructure even unviable loans and effectively hide stress in their balance sheets; by the time forbearance ended in 2015, restructuring had increased sevenfold and NPAs had nearly doubled compared with pre-forbearance levels. The subsequent RBI Asset Quality Review was intended to uncover this hidden stress. The lesson is that postponing an unpleasant decision may provide temporary relief, but it can also allow the underlying problem to grow."]},
  "The precautionary principle in environmental clearance: when is delay itself the protection?":{
    t:"Precautionary principle in environmental clearance",
    p:["However, delay is not always a failure of decision-making. Sometimes the responsible decision is to wait when an action could cause irreversible harm. In Vellore Citizens' Welfare Forum v. Union of India, the Supreme Court held that where there is a threat of serious or irreversible environmental damage, lack of scientific certainty should not be used as a reason to postpone preventive measures. Thus, a project may need closer assessment before approval when its environmental consequences are uncertain but potentially permanent. The important distinction is between deliberate waiting to prevent harm and indecision caused by fear or avoidance."]},
  "Bureaucratic risk aversion, the Prevention of Corruption Act amendments and honest-decision protection":{
    t:"Prevention of Corruption Act and bureaucratic risk aversion",
    p:["Too much fear of making a wrong decision can itself produce administrative paralysis. Officials may hesitate to take bona fide decisions if they fear that a decision made today could later become the basis of a corruption investigation. The 2018 amendment to the Prevention of Corruption Act inserted Section 17A, requiring prior approval before an inquiry or investigation into an offence related to a public servant's recommendation or decision taken in the discharge of official functions, subject to specified exceptions. The provision was intended to protect genuine decision-making from harassment, but the larger administrative issue is clear: when every imperfect decision appears personally risky, officials may prefer to postpone decisions altogether."]},
  "Climate policy where the cost of acting is visible and the cost of waiting is not":{
    t:"Climate policy",
    p:["Climate change creates a different form of decision-making problem: the cost of action is immediate, while the cost of inaction is delayed. Governments may have to bear visible short-term costs by changing energy systems, restricting emissions or investing heavily in adaptation and clean technology. The consequences of postponement, however, accumulate gradually and are easier to ignore politically. The World Bank notes that the cost of climate impacts is rising and that early, proactive resilience-building is more cost-effective than waiting for worse impacts to arrive. Climate policy therefore shows how a decision not to act today can quietly increase the cost of action tomorrow."]},
  "Evidence-based policy and randomised trials — what they establish and what they cannot":{
    t:"What a trial establishes and what it cannot",
    p:["The 2019 Nobel in economics went to Abhijit Banerjee, Esther Duflo and Michael Kremer for bringing randomised controlled trials into development economics, beginning with Kremer's schooling experiments in Kenya in the mid-1990s. The method's strength is internal validity. Randomisation removes self-selection, so the measured difference can fairly be attributed to the intervention rather than to who signed up for it. The recognised weakness is external validity. Angus Deaton and Nancy Cartwright have argued that a result established in one place at one scale does not travel automatically, because the mechanism producing it may depend on local conditions. A trial tells you something worked there. It does not by itself tell you it will work here."]},
  "NITI Aayog indices and the risk that a metric becomes the objective":{
    t:"When the measure becomes the target",
    p:["Goodhart's law holds that when a measure becomes a target, it ceases to be a good measure. Campbell's law makes the sharper claim that the more a quantitative social indicator is used for decision-making, the more it will distort the process it was meant to monitor. India measures heavily. The SDG India Index tracks states across 113 indicators aligned to the National Indicator Framework, and the Aspirational Districts Programme, launched in January 2018, ranks 112 districts on health, education, agriculture and infrastructure through periodic delta rankings. Ranking produces real improvement and a real incentive to manage the number. The test for any index is whether it rewards the underlying outcome or only the reported one."]},
  "Best-practice transplantation: models that worked in one state and failed in another":{
    t:"A model that travels, and what it needs to survive the journey",
    p:["The mid-day meal shows both halves of this. M. G. Ramachandran launched the noon meal scheme in Tamil Nadu on 1 July 1982. A national programme followed in 1995, and on 28 November 2001, in the right to food case, the Supreme Court directed every state to provide a cooked meal of at least 300 calories and 8 to 12 grams of protein for a minimum of 200 school days. The design travelled. The administrative capacity did not travel with it. On 16 July 2013 at Gandaman in Saran district, Bihar, 23 children died after eating a meal cooked in oil taken from a container that had held the pesticide monocrotophos. The scheme was identical. The kitchen was not."]},
  "Algorithmic decision support in credit, policing and welfare targeting":{
    t:"When the default is denial",
    p:["An automated check has a default, and the default carries the moral weight. Jean Drèze and colleagues surveyed around 1,000 households across 32 villages in Jharkhand and found exclusion rates as high as twenty per cent where every ration sale required biometric authentication. A fingerprint that fails to match is treated as a failed claim rather than a failed sensor, so the system's error becomes the claimant's loss. The Right to Food Campaign documented at least 57 hunger-related deaths between 2015 and 2018, of which at least 19 were linked to Aadhaar-related exclusion from the public distribution system. The design question is not whether the algorithm is accurate on average. It is who bears the cost when it is wrong."]},
  "Field experience versus headquarters analysis in district administration":{
    t:"What the field knows that the file does not",
    p:["The smallpox campaign is the clearest case of field knowledge overturning central doctrine. The received strategy was mass vaccination, and by the early 1970s headquarters could point to rising coverage figures while transmission continued. Epidemiologists working in Bihar and Uttar Pradesh established that the disease was being sustained by clusters that broad campaigns kept missing, and the strategy shifted to active search and containment: find each case, then vaccinate the ring of contacts around it. Coverage had been the wrong measure and interruption of transmission was the right one. Headquarters can see the aggregate and the field can see the mechanism. Policy fails when the aggregate is mistaken for the mechanism."]},
  "Sabarimala, triple talaq and the courts as arbiter between custom and constitutional right":{
    t:"The courts between custom and constitutional right",
    p:["Two judgments define the modern position. In Shayara Bano v Union of India, decided on 22 August 2017, a five-judge bench struck down instant triple talaq by 3:2, holding it arbitrary and not protected by Article 25. Parliament followed with the Muslim Women (Protection of Rights on Marriage) Act 2019. In Indian Young Lawyers Association v State of Kerala, decided on 28 September 2018, a bench held by 4:1 that excluding women aged 10 to 50 from the Sabarimala temple was unconstitutional, Justice Indu Malhotra dissenting. The contrast is the useful part. Legislative follow-through settled the first. The second drew more than fifty review petitions and a reference that remains undecided."]},
  "Article 25 and the essential religious practices doctrine — who decides what is essential":{
    t:"Who decides what is essential",
    p:["The essential religious practices doctrine comes from the Shirur Mutt case of 1954, where a seven-judge bench held that what is essential to a religion is to be determined by reference to the doctrines of that religion itself. The consequence is awkward. A constitutional court must settle a theological question before it can settle a legal one. Sabarimala pushed this to its limit. In November 2019 the review petitions were kept pending and the larger questions were referred to a nine-judge bench, which began hearings on 7 April 2026 and reserved judgment on 14 May 2026, with 66 related matters tagged to it. Until it rules, the test that decides these disputes is itself under reconsideration."]},
  "Khap panchayats, honour crimes and social sanction operating below the law":{
    t:"Sanction that operates below the law",
    p:["In Shakti Vahini v Union of India (2018), the Supreme Court held that when two consenting adults choose each other the choice is protected by Articles 19 and 21, and that assemblies gathering to punish such a marriage act illegally. The Court directed states to create special cells in every district, safe houses for threatened couples and a round-the-clock helpline. The wider point is about where the sanction actually sits. No statute authorises these bodies and their power does not come from law. It comes from the willingness of a village to enforce their verdict socially. A right that is legally secure can still be practically unavailable when the community around it disagrees."]},
  "The conservative case: Burkean caution about dismantling institutions faster than they can be replaced":{
    t:"Burke's caution about dismantling faster than you can replace",
    p:["Edmund Burke's Reflections on the Revolution in France, published in 1790, is the strongest statement of the case for caution. His argument is not that inherited institutions are good. It is a claim about knowledge. An institution that has lasted carries accumulated adjustments whose reasons are no longer visible, so a reformer who cannot see the reason may still be removing something load-bearing. He therefore preferred reform that repairs to reform that replaces. Using Burke honestly means stating the objection as well. The same argument was used to defend sati, caste disability and every practice later abolished. Caution is a reason to move carefully. It is not a reason not to move."]},
  "Reform from within a tradition versus reform imposed on it — Vidyasagar, Roy, and their limits":{
    t:"Vidyasagar, Roy, and the limits of arguing from inside",
    p:["Both men worked from inside the tradition rather than against it. Raja Ram Mohan Roy campaigned against sati using Sanskrit scholarship to argue the practice had no scriptural warrant, and the Bengal Sati Regulation was issued by Lord William Bentinck on 4 December 1829. Ishwar Chandra Vidyasagar, principal of Sanskrit College, published his case for widow remarriage in 1855, arguing from the Parashara Smriti that the texts permitted it, and the Hindu Widows' Remarriage Act followed in 1856. Both won the argument and both met the same wall. Legality is not acceptance. Widow remarriage stayed rare for generations, which is the standing limit of reform that changes the statute before it changes the sanction."]},
  "Directive Principles as non-justiciable ideals that have nonetheless shaped legislation":{
    t:"Ideals that cannot be enforced but still legislate",
    p:["Article 37 states that the Directive Principles are not enforceable by any court and are nevertheless fundamental in the governance of the country. That reads like a contradiction and works as a programme. Article 45 on free and compulsory education sat unenforceable for over fifty years, until the 86th Amendment of 2002 inserted Article 21A and made elementary education a fundamental right, which the Right of Children to Free and Compulsory Education Act 2009 then operationalised. Article 39A produced the Legal Services Authorities Act 1987. Article 41 on the right to work stands behind MGNREGA in 2005. The mechanism is slow and real. A directive becomes a statute, and the statute creates the enforceable right."]},
  "Preambular values against measured outcomes — the annual audit an essay can perform":{
    t:"The annual audit an essay can perform",
    p:["This prompt is a method rather than an example, and it is worth practising before the exam. The Preamble commits the state to justice in its social, economic and political forms, to liberty of thought and belief, to equality of status and opportunity, and to fraternity assuring the dignity of the individual. Each term has measurable proxies. Economic justice can be read against consumption and wage data, equality of opportunity against school completion and labour force participation broken down by group, dignity against conviction rates in atrocity cases. The exercise is to set the commitment beside the number and state the distance plainly, without dismissing the ideal as rhetoric or treating an improvement as arrival."]},
  "SDG 2030 targets and the honest arithmetic of India's distance from them":{
    t:"The honest arithmetic of the distance",
    p:["NITI Aayog's SDG India Index is the cleanest available measure of where India stands. The composite score moved from 57 in 2018 to 66 in 2020-21 and to 71 in 2023-24, measured across 113 indicators aligned to the National Indicator Framework. State and union territory scores now range from 57 to 79, against a range of 42 to 69 in 2018, with Uttarakhand and Kerala at the top. Climate action showed the largest single gain, rising from 54 to 67. Two readings follow and a good essay carries both. The direction is genuinely positive and the floor has risen substantially. On most goals the distance still to cover by 2030 remains large."]},
  "Disaster preparedness and fiscal prudence as roof-repair in good weather":{
    t:"Repairing the roof in good weather",
    p:["Preparedness is the clearest case of spending now against a cost that may never visibly arrive. The Disaster Management Act 2005, in force from January 2006, built a three-tier structure of national, state and district authorities, with the National Disaster Management Authority chaired by the Prime Minister. India's National Disaster Management Plan of 2016 was the first national plan explicitly aligned to the Sendai Framework, whose four priorities for action include investing in disaster risk reduction for resilience. The political difficulty is structural. Money spent on preparedness produces no visible event and no gratitude, while money spent on relief produces both. Fiscal consolidation in good years is resisted for exactly the same reason."]},
  "The cynic's objection: unreachable ideals as a licence for permanent underperformance":{
    t:"Unreachable ideals as an excuse for permanent underperformance",
    p:["The objection deserves its strongest form. If a standard can never be met then it can never be failed, so it becomes a permanent alibi. Any shortfall is explained by the difficulty of the ideal rather than by anyone's decision. The Directive Principles were attacked on exactly this ground in the Constituent Assembly, as a promise the state need never honour. The reply is that an unreachable standard is not the same as an unusable one. Article 45 was unenforceable for over fifty years and still produced Article 21A and the 2009 Act. The test is whether an ideal generates a direction and a schedule, or only a vocabulary for explaining why nothing moved."]},
};
