/* =====================================================================
   WORKS IN DEPTH
   ---------------------------------------------------------------------
   Five thinkers, one from each of five different traditions, chosen to be
   as unlike each other as the roster allows: an aphoristic poem, a state
   manual, an economics, a polemic and a pair of novels, spread across
   roughly twenty-five centuries.

   Keyed by thinker id. Each entry:
     t      title of the piece
     why    one line on why this thinker was picked from that tradition
     intro  the framing, before any individual work
     works  one section per work; `t` matches the title in works.js exactly,
            which is what lets a Major Works card link straight to it
     close  what the body of work is for, and what it is worth in the exam

   Roughly 1,000 words each. **double asterisks** render as bold.
   ===================================================================== */

const WORKLAB = {

"laozi":{
  t:"Eighty-one poems that begin by disqualifying themselves",
  why:"Chosen from the Eastern traditions because it is the only classic of political advice that argues entirely by paradox, and instructs the ruler to do less.",
  intro:["Most foundational books open by telling you what they are about. The Tao Te Ching opens by telling you that it cannot. **The Tao that can be named is not the eternal Tao** — the first line of the first chapter, disqualifying in advance everything that follows in the remaining eighty. No other work in the world's canon starts by admitting that its subject cannot survive being written down, and then writes five thousand characters anyway.",
         "That refusal is not modesty and it is not mysticism for its own sake. It is a claim about language: that words operate by division, cutting the world into categories, while the thing being described does not come divided. Any statement precise enough to be useful has therefore already falsified something. What follows in the text is an attempt to work around that limit by using contradiction as an instrument rather than treating it as an error."],
  works:[
    {t:"Tao Te Ching",
     p:["The physical facts are modest and slightly disputed. Around five thousand Chinese characters, arranged in eighty-one very short chapters, traditionally attributed to Laozi — a name that means little more than **Old Master** — and probably assembled over generations rather than composed by one person. The bamboo-slip versions recovered at Guodian in 1993 are older than any text previously known and are arranged in a different order, which suggests a work that circulated as sayings before it settled into a book. It is, after the Bible, among the most translated works ever written, and no two translations agree, because classical Chinese marks neither tense nor number nor, frequently, the subject of a sentence.",
        "The central concept is **wu wei**, usually rendered as non-action and almost always misunderstood. It does not mean doing nothing. It means acting without forcing — moving with the grain of a situation rather than against it, and recognising that a great deal of what people do to accelerate an outcome delays it. The image the text keeps returning to is agricultural: the farmer who pulls the seedling upward to help it grow. Effort applied in the wrong direction is not neutral, it is destructive, and the discipline is knowing which direction that is.",
        "Water carries most of the argument, and the choice of image is the argument. Water is the softest substance and wears through stone. It takes the shape of whatever contains it and is not diminished by doing so. It seeks the low ground that everyone else avoids, which is exactly why everything eventually flows to it. A philosophy that wanted to praise strength would have chosen a different image; this one is proposing that yielding is a form of power, and that the appearance of weakness is frequently the strategy rather than the condition.",
        "What is easy to miss, reading it as spirituality, is that a substantial part of the book is addressed to a ruler. It was written during the Warring States period, when Chinese states were consuming each other and the rival Legalist school was arguing for elaborate law, heavy punishment and total administrative control. Against that, the Tao Te Ching advises: **govern a large state the way you would cook a small fish** — which is to say, stop turning it over. The best ruler, it says, is the one whose people barely know he exists; the next best is loved; the next feared; and the worst is despised. When the work is done, the people should say they did it themselves.",
        "The paradoxes are structural rather than decorative, and they repay being taken literally. Thirty spokes meet at a hub, and it is the empty space at the centre that makes the wheel useful. Clay is shaped into a pot, and the pot's usefulness is the emptiness inside it. Doors and windows are cut into a room, and the room is useful because of what is not there. The recurring move is to relocate value from the substance to the absence — a way of thinking that is almost the opposite of how a modern policy document is constructed, and considerably more useful when the question is whether to add another rule.",
        "The honest difficulty with the text is that it has been read as quietism, and that reading is available. A book which says that the sage acts without striving, that knowing when to stop avoids danger, and that the softest overcomes the hardest, can be quoted by anyone who wants a reason not to act — and has been, by rulers who found it convenient. It also offers no institutional design whatever. There is no constitution here, no separation of powers, no mechanism by which a bad ruler is removed; the whole argument rests on the ruler's restraint, which is precisely the variable a political system exists to stop depending on."]}
  ],
  close:["What survives the difficulty is a disposition that Indian governance could use more of. The instinct to legislate a problem, to add a compliance requirement, to notify a scheme, treats action as inherently virtuous and inaction as failure — and produces a regulatory landscape nobody can navigate. The Tao Te Ching's contribution to that argument is not an answer but a permanent question: whether the intervention being proposed will work with the grain of the situation or against it, and whether the person proposing it can tell the difference.",
         "**For the Essay paper it is the most useful text in the world for questions about simplicity, restraint, change and the limits of control.** Muddy water is best cleared by leaving it alone comes from this tradition. So does the case against it, because knowing which water clears and which is being poisoned upstream is exactly the judgement the book declines to supply."]
},

"kautilya":{
  t:"The manual that disappeared for fifteen hundred years",
  why:"Chosen from Indian Classical thought because it is the least philosophical and most startling text in the tradition — an operating manual for a state, written by someone who had run one.",
  intro:["In 1905 a pandit walked into the Mysore Oriental Library and handed the librarian a bundle of palm leaves. The librarian, R. Shamasastry, recognised what he was holding: the **Arthashastra**, a work that scholars had known about for centuries entirely by reputation, because later authors kept citing it and nobody had seen a copy. It had been lost for something like fifteen hundred years. He published the Sanskrit text in 1909 and an English translation in 1915, and the effect on how India understood its own political past was immediate and permanent.",
         "What emerged was not what anyone expected. Indian classical thought was, in the colonial account and in much of the nationalist one, spiritual, otherworldly and uninterested in the mechanics of power. The Arthashastra is a fifteen-book operating manual concerned with revenue collection, mining rights, irrigation, famine reserves, espionage, poisons, fort construction, the regulation of prostitution, the treatment of slaves, and the exact hour at which a king should wake."],
  works:[
    {t:"Arthashastra",
     p:["The structure tells you what kind of book it is. Around six thousand sutras across fifteen books, written in compressed prose, organised by function rather than by argument. There is no attempt to justify the state's existence, no myth of origin doing philosophical work, no extended treatment of what the good life consists in. It opens with the training of a prince and proceeds to the duties of superintendents — of gold, of the storehouse, of ships, of cows, of weaving — in the manner of an administrative handbook, which is what it is.",
        "The most quoted contribution is the **mandala** theory of interstate relations, and it is more subtle than the slogan. States are arranged in concentric circles of interest, with the immediate neighbour a natural rival because you share a border worth disputing, and the neighbour's neighbour a natural ally because you share that rival. From this follows the **sixfold policy** — peace, war, neutrality, preparation, alliance and duplicity — chosen not by affinity or ideology but by an honest assessment of relative strength. A weaker state selects differently from a stronger one, and pretending otherwise is how weak states get destroyed.",
        "The fourfold sequence is the part with the most contemporary force: **sama, dana, bheda, danda** — conciliation, inducement, division, and force, in that order. Force comes last, and not for moral reasons. It is the most expensive instrument available, the least predictable in its results, and it destroys what you were trying to acquire. A ruler who reaches for it first has revealed that he could not manage the other three. This is the intellectual ancestry of the claim that the supreme art of war is to subdue the enemy without fighting, and in Kautilya's hands it is a cost argument rather than a pacifist one.",
        "The espionage apparatus is where modern readers usually flinch, and they should. The text describes a network of agents operating under cover as ascetics, merchants, householders and cooks; it discusses entrapment, assassination, the use of poison, and the deliberate manufacture of a pretext for war. It also describes judicial torture with the same procedural calm. Any honest account has to say that this is a surveillance state described approvingly by someone who had helped build one, and that a great deal of it would be criminal under the Constitution the same country later wrote.",
        "And yet the text is not amoral in the way Machiavelli is usually caricatured as being, which is the detail most often left out. It states plainly that **in the happiness of his subjects lies the king's happiness; in their welfare, his welfare** — and it means this operationally rather than sentimentally. There are provisions for famine relief, for remitting taxes after crop failure, for state support of the old, the sick, orphans and destitute women, for the maintenance of irrigation works, and for a king whose entire day is divided into eighths with specific duties in each. The realism runs in both directions: a ruler who impoverishes his people is not wicked so much as incompetent, because he will not have a kingdom for long.",
        "The authorship question deserves a straight answer, because it is frequently muddled. The text identifies its author as Kautilya, also called Vishnugupta, traditionally identified with Chanakya, the minister who is supposed to have installed Chandragupta Maurya around 320 BCE. Most scholars now think the work as we have it is a compilation assembled and revised over several centuries, with a core that may well be Mauryan. That does not diminish it. It means we are reading the accumulated administrative knowledge of a civilisation rather than the opinions of one clever man."]},
    {t:"Chanakya Niti",
     p:["This is a different book and it is worth separating them, because in India they are constantly conflated. **Chanakya Niti** is a later collection of aphorisms on prudence, friendship, money, family and character — closer to a wisdom anthology than to a treatise on government. Do not live in a country where you are not respected, cannot earn a living, and have no friends. Test a servant on duty, a relative in difficulty, a friend in adversity, and a wife in misfortune.",
        "It is by some distance the more widely read of the two in India today, sold at railway stations and quoted in self-improvement books, and much of what is popularly attributed to the Arthashastra actually comes from here or from nowhere at all. For an essay, that distinction matters. Citing the Arthashastra for a maxim about choosing friends is the kind of error an examiner notices."]}
  ],
  close:["What makes the Arthashastra permanently useful is that it is written from inside the problem. It does not ask whether the state should do difficult things; it assumes the state exists, that its neighbours are hostile, that its officials will steal, and that its ruler will be tempted — and then sets out procedures for each. The chapters on detecting embezzlement by officials read like an audit manual, because that is what they are, and they list forty distinct methods of misappropriation.",
         "**For the Essay paper it is indispensable on ends and means, on statecraft and asymmetry, and on the ethics of public office.** It is also the standing rebuttal to anyone who claims that concern with administrative detail is a modern or Western preoccupation. India was writing procedure manuals when the alternative was myth."]
},

"marx":{
  t:"A pamphlet, two abandoned notebooks and an unfinished economics",
  why:"Chosen from modern Western political thought because no other body of work has been acted on by more governments, and because most of it was never published while he was alive.",
  intro:["The most consequential political writer of the modern era published a fraction of what he wrote. Two of the works that most shaped how he was read in the twentieth century sat unpublished for **eighty-five years** and appeared only in 1932, by which time states had already been founded in his name by people who had never seen them. The third and fourth volumes of his major work were assembled from notebooks by Engels after his death. It is a strange bibliography for a body of thought that changed the political map.",
         "Reading the works in the order he wrote them, rather than in order of fame, produces a different Marx from the one most people argue about — one who begins with a question about what work does to a person and only later builds the economics to answer it."],
  works:[
    {t:"Economic and Philosophic Manuscripts",
     p:["Written in Paris in 1844 when he was twenty-six, abandoned, and not published until 1932. These notebooks contain the concept that has travelled furthest outside economics: **alienation**. Work under industrial conditions, Marx argued, estranges the worker four times over — from the product, which belongs to someone else the moment it exists; from the activity, which is not chosen and offers nothing back; from other workers, who become competitors; and from what he called species-being, the human capacity for free conscious creation that work was supposed to express.",
        "The discovery of these manuscripts in the 1930s split Marxism. Here was a young Marx concerned with dignity, self-realisation and the quality of a life, rather than with the falling rate of profit — and an entire humanist tradition grew from them, in France, in Yugoslavia, and among people who wanted the moral argument without the state that had been built on the economic one. For the modern reader the manuscripts are the reason Marx remains relevant to a debate about automation. They separate the question of whether work exists from the question of whether it is worth doing."]},
    {t:"The German Ideology",
     p:["Written with Engels in 1846, also abandoned, also unpublished until 1932. Marx later remarked that they had left the manuscript **to the gnawing criticism of the mice**, having achieved their main purpose, which was self-clarification. What it sets out is historical materialism: the claim that ideas, law, religion and morality are not independent forces driving history but arise from the material conditions of production. It is not consciousness that determines life, but life that determines consciousness.",
        "It also contains the strangest and most human passage in Marx: a communist society in which it is possible to hunt in the morning, fish in the afternoon, rear cattle in the evening and criticise after dinner, without ever becoming hunter, fisherman, herdsman or critic. The point is not the agricultural detail. It is that the division of labour, which economics treats as pure gain, also assigns a person a permanent identity they did not choose."]},
    {t:"The Communist Manifesto",
     p:["Commissioned by the Communist League and written at speed, this is about twelve thousand words — an afternoon's reading — published in February 1848, weeks before revolution broke out across Europe. Its power is rhetorical as much as analytical, and it knows it: **a spectre is haunting Europe** is a first line written by someone who understood that a political argument has to be heard before it can be examined.",
        "What surprises most first readers is how admiring it is of capitalism. The bourgeoisie, it says, has accomplished wonders surpassing the pyramids and the cathedrals, has created more massive productive forces than all preceding generations together, and has torn away every ancient certainty so that **all that is solid melts into air**. The critique is not that capitalism failed to deliver. It is that it delivers by continuously destroying, and that the class it created to run its machines will eventually run it. As prophecy the pamphlet has a mixed record; as a description of what industrialisation does to settled societies it has aged remarkably well."]},
    {t:"Das Kapital",
     p:["Only the first volume appeared in his lifetime, in 1867, after two decades of work conducted largely in the Reading Room of the British Museum. Engels assembled the second and third volumes from notebooks after Marx's death, and the fourth exists as a separate collection of critiques. This is the technical work, and it is genuinely difficult — the opening chapters on the commodity are among the hardest pages in the history of economics.",
        "The architecture rests on the labour theory of value and the concept of **surplus value**: the worker is paid for their capacity to work, produces more value than that capacity costs, and the difference is where profit comes from. Around this Marx builds an account of accumulation, of the concentration of capital, and of the tendency of the rate of profit to fall. Mainstream economics abandoned the labour theory of value within a generation, and it is important to say so plainly rather than defend it.",
        "What survives independently of that theory is **commodity fetishism** — the observation that under market conditions a relationship between people appears as a relationship between things. A price seems to be a property of an object, like weight, rather than the residue of who made it and under what conditions. Anyone who has looked at a garment's price tag and not thought about the person who stitched it has experienced exactly what Marx was describing, and no competing framework names it as well."]}
  ],
  close:["India's engagement with these texts has been unusually direct. They shaped the planning apparatus after independence, the trade union movement, the land reform debates in Kerala and West Bengal, and the insurgencies that are still being fought in parts of the country. The most instructive Indian response, though, is Ambedkar's: that a framework built on class cannot explain caste, because caste divides the working class against itself and no amount of economic transformation touches it while the graded inequality survives. It is the sharpest critique Marx has received from anyone who took him seriously.",
         "**For the Essay paper the useful Marx is rarely the revolutionary one.** He is the indispensable authority on alienation and the meaning of work, on inequality and its mechanics, on history as a process with a material logic, and on the difference between what an economy produces and what it does to the people inside it."]
},

"ambedkar":{
  t:"A speech too dangerous to deliver",
  why:"Chosen from the Indian Renaissance because no other Indian thinker changed register so completely — from monetary economics to constitutional drafting to founding a religion — or was so systematically read out of the record.",
  intro:["In 1936 a reformist organisation in Lahore, the Jat-Pat Todak Mandal, invited Ambedkar to deliver its annual presidential address. They asked, reasonably, to see the text in advance. What they read alarmed them so completely that they requested he remove sections of it; when he refused to alter a word, they cancelled the conference. **He then printed fifteen hundred copies at his own expense.** It sold out, and Annihilation of Caste has never since been out of print.",
         "That is the story of the most famous work, and it is characteristic. Ambedkar's bibliography is not a career; it is a sequence of interventions, each aimed at a specific institution that had refused him, and each conducted in whatever discipline the intervention required."],
  works:[
    {t:"The Problem of the Rupee",
     p:["This came first, and almost nobody expects it. Submitted as his doctoral thesis at the London School of Economics and published in 1923, it is a technical monograph on Indian currency, arguing against the gold exchange standard the colonial administration favoured and in favour of a gold standard with a fixed, stable rupee. His central concern was inflation: a managed currency, he argued, hands the administration a mechanism for imposing a hidden tax that falls hardest on people with no assets to hedge with.",
        "He gave evidence to the Hilton Young Commission, whose recommendations led to the establishment of the Reserve Bank of India in 1935, and the intellectual debt is real if indirect. The fact that the man who drafted the Constitution began as a monetary economist trained under Edwin Cannan is not a piece of trivia. It explains why his later constitutional writing is unusually attentive to what a provision will actually cost and who will bear it."]},
    {t:"Annihilation of Caste",
     p:["The undelivered speech is an argument built to close every exit. Caste is not, he insists, a division of labour but **a division of labourers** — a hierarchy of workers, arranged so that each stratum has someone beneath it and therefore an interest in the whole arrangement. This is why it survives without needing enforcement: it is maintained by the graded structure of its own beneficiaries.",
        "From this follows the conclusion that made his hosts cancel the conference. If caste is sustained by religious sanction, then reform of caste practices is beside the point, and inter-caste dining will change nothing. What must be attacked is the authority of the shastras themselves — **you must destroy the religion of the shrutis and the smritis**, he wrote, and there is no polite way to say that to a Hindu reform organisation.",
        "The text's afterlife is as important as the text. Gandhi replied in Harijan, defending varna while condemning untouchability, and arguing that a religion should be judged by its best adherents rather than its worst practices. Ambedkar published Gandhi's response and his own reply in the second edition — an unusual and confident editorial decision — and the resulting exchange is among the most consequential published arguments in Indian political thought. Reading only one side of it, as most people do, misses what makes it formidable."]},
    {t:"States and Minorities",
     p:["Submitted to the Constituent Assembly in 1947 on behalf of the Scheduled Castes Federation, this is the document that shows what Ambedkar would have written had he been drafting alone. It proposes a scheme of constitutional safeguards for minorities, and it proposes **state socialism** as a constitutional obligation rather than a policy choice: key industries state-owned, insurance nationalised, and agriculture reorganised as collective farms with the state as landlord.",
        "Almost none of the economic content survived into the Constitution, and the safeguards that did survive were narrowed. The document is therefore the best available answer to a question people often ask about him — whether the Constitution represents his views. It largely does not, and he said so himself, remarking in 1953 that he would be the first to burn it, because it had not delivered what he had built it to deliver."]},
    {t:"The Buddha and His Dhamma",
     p:["Completed shortly before his death and published posthumously in 1957, this is a reconstruction rather than a translation — Buddhism presented as a social ethic, with the supernatural, the doctrine of rebirth in its literal form, and much of the monastic apparatus removed or reinterpreted. Suffering, in his account, is largely social in origin, and the Dhamma is a programme for a just society rather than a route out of the world.",
        "Buddhist scholars have criticised it, sometimes sharply, for departing from the canonical texts, and the criticism is not unfounded. But it is a mistake to read it as failed scholarship. It was written as a scripture for a community he was in the act of creating: in October 1956, at Nagpur, he converted to Buddhism along with something in the order of half a million people, having spent twenty years saying he would not die a Hindu. He died seven weeks later. The book is the text that community was given."]}
  ],
  close:["The arc from a monetary thesis to a new scripture is not a career anyone plans, and it is the most revealing thing about the corpus. Each work is aimed at a particular door that had been closed: the colonial economic establishment, the Hindu reform movement, the Constituent Assembly, and finally the religion itself. When the argument failed to open the door, he did not moderate it. He changed disciplines and attacked from a different side.",
         "**For the Essay paper Ambedkar is the strongest single authority on caste, social justice, constitutional morality and minority rights**, and the most useful corrective to any argument that treats Indian social reform as a settled achievement. He is also the standing evidence that a person can be a technical economist, a constitutional draftsman and a religious founder without any of the three being a hobby."]
},

"orwell":{
  t:"Fiction as a form of evidence",
  why:"Chosen from the global humanist voices because he is the only major political thinker who concluded that the argument could not be won in essays, and wrote novels instead.",
  intro:["Two of the most politically consequential books of the twentieth century are a fable about farm animals and a novel about a clerk who falsifies newspapers. Neither is a work of political theory; both were written by a man who had already made the same arguments in essays and journalism and watched them fail to land. **The decision to switch to fiction was a considered judgement about persuasion**, and understanding why he made it is the key to the whole body of work.",
         "The turning point was Spain, and everything before it reads as preparation."],
  works:[
    {t:"Homage to Catalonia",
     p:["Published in 1938, this is the account of his six months fighting fascism in the Spanish Civil War — including being shot through the throat by a sniper and surviving by a margin of millimetres. It sold roughly six hundred copies in his lifetime and the print run had not sold out when he died. It is nonetheless the hinge on which his whole career turns.",
        "What changed him was not the fighting. It was discovering that the militia he had served in was being retrospectively described in the international press as a fascist fifth column, that comrades were being arrested and shot by their own side, and that respectable newspapers in London were reporting a version of events he had personally watched not happen. **He had seen a record being rewritten while the event was still in progress.** Everything afterwards, including both novels, is an attempt to explain that experience to people who had not had it."]},
    {t:"Animal Farm",
     p:["Finished in 1944 and rejected by four publishers, including T. S. Eliot at Faber, who thought the animals' point of view unconvincing. The real objection was political: Britain was allied with the Soviet Union, the book was an unmistakable allegory of the Russian Revolution, and nobody wanted to publish an attack on an ally during a war. It appeared in August 1945, and the timing did the rest.",
        "The choice of the fable form is the craft decision worth studying. A direct polemic against Stalinism in 1945 would have been read as a political position and filed accordingly by readers who had already chosen a side. A story about pigs is read before the reader has decided what to resist, and by the time the commandments on the barn wall have been quietly amended to say that all animals are equal but some are more equal than others, the argument has already been made and accepted. Orwell was doing deliberately what a treatise cannot do — getting past the reader's defences."]},
    {t:"Politics and the English Language",
     p:["The 1946 essay is the theoretical statement underneath both novels, and it is six pages long. Its claim is that the decline of language is not merely an aesthetic matter: vague, stale and euphemistic prose makes it possible to hold indefensible positions, because the words no longer summon the pictures. **Political language is designed to make lies sound truthful and murder respectable.** Defenceless villages are bombarded and the operation is called pacification.",
        "The six rules he ends with are still the best short guide to writing in English, and the last one undercuts the other five: break any of these rules sooner than say anything outright barbarous. What makes the essay permanently useful for an Indian reader is the list of official euphemisms it invites you to compile for yourself. Encounter. Collateral. Rationalisation. Relocation. Each one is a phrase constructed so that a thought cannot form."]},
    {t:"Nineteen Eighty-Four",
     p:["Written on the island of Jura between 1946 and 1948 while he was dying of tuberculosis, typing the final draft himself because he could not find a typist willing to come to the island. He died seven months after publication, aged forty-six. The novel supplied the modern vocabulary for describing state power almost single-handedly: **Newspeak**, **doublethink**, the memory hole, thoughtcrime, the Ministry of Truth, and the observation that whoever controls the past controls the future.",
        "The most underrated feature is the appendix. The Principles of Newspeak is written in standard English, in the **past tense**, describing the regime's language as a historical phenomenon — which implies, quietly, that Oceania fell and that someone survived to write the essay. Almost no reader notices, and it changes the book from a prophecy of permanent defeat into something considerably more open.",
        "What the novel gets wrong is as instructive as what it gets right. Orwell imagined surveillance as a cost the state bears — a telescreen in every room and an army of watchers. The version that arrived is one where the citizen buys the device, carries it voluntarily, and generates the data as a by-product of enjoying themselves. The mechanism he described has been more than realised; the economics have been inverted."]}
  ],
  close:["The afterlife of these books is a small case study in what he was writing about. **Orwellian** is now used by almost everyone, frequently to describe things Orwell would have supported, and both left and right claim him — which is possible only because most people who invoke him have read the two novels and none of the journalism. He was a democratic socialist who fought in a militia, and he is routinely cited as an authority against socialism.",
         "The record should also include the part his admirers skip. In 1949, ill and near the end, he gave a list of writers he considered unreliable to a friend working for the Information Research Department, a British government propaganda unit. It is a genuinely uncomfortable fact about a man whose central subject was the corruption of institutions by the demand for loyalty, and any honest treatment has to hold it alongside the work.",
         "**For the Essay paper he is the primary authority on media, propaganda, surveillance, language and the manipulation of the historical record** — and the best available demonstration that a political argument sometimes travels further as a story than as a case."]
}

};
